import { useState, useMemo, useRef, useCallback } from "react";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import {
  UploadCloud, FileSpreadsheet, X, Download, AlertTriangle, KeyRound,
  Users, GraduationCap, TrendingUp, ChevronDown, ChevronRight,
} from "lucide-react";

// ---------- constants ----------
const NAVY = "#1B2A4A";
const NAVY_SOFT = "#2E4269";
const GOLD = "#B8860F";
const GOLD_SOFT = "#D9A93A";
const PAPER = "#FAF7F0";
const PAPER_LINE = "#E7E0D0";
const INK = "#26241C";
const SLATE = "#6B6656";
const GREEN = "#3D6B4F";
const RUST = "#A8452F";

const COMPLETE_THRESHOLD = 99.5;

// ---------- helpers ----------
function parseCell(raw) {
  if (raw === null || raw === undefined || raw === "") return { value: 0, notStarted: true };
  if (typeof raw === "number") return { value: raw, notStarted: raw <= 0 };
  const str = String(raw);
  const match = str.match(/-?\d+(\.\d+)?/);
  const num = match ? parseFloat(match[0]) : 0;
  const notStarted = /not started/i.test(str) || num <= 0;
  return { value: num, notStarted };
}

// Section identity always comes from the actual "Groups" column value on the
// row itself (groupStr) — this is what lets a single combined workbook with
// many sections mixed into one sheet split apart correctly, and what lets
// individual per-section files still work the same way. The filename is only
// ever a fallback for the rare row with a blank Groups cell.
function parseSectionMeta(groupStr, fileName) {
  const source = (groupStr && String(groupStr).trim()) || fileName;
  const m = String(source).match(/(\d{4}-\d{4})-([A-Za-z]+)-([A-Za-z0-9]+)/);
  if (m) {
    return {
      batch: m[1],
      branch: m[2].toUpperCase(),
      section: m[3].toUpperCase(),
      label: `${m[2].toUpperCase()}-${m[3].toUpperCase()}`,
    };
  }
  // No "batch-branch-section" pattern found — trust the raw Groups value
  // itself as the section identity rather than collapsing everything down
  // to the filename, which is what a combined multi-section sheet needs.
  return { batch: "—", branch: "General", section: source, label: source };
}

function shortCourseLabel(header) {
  let h = String(header).replace(/\s*\(%\)\s*$/i, "").trim();
  const parts = h.split(" - ");
  return parts[0].trim();
}

function courseCode(header) {
  let h = String(header).replace(/\s*\(%\)\s*$/i, "").trim();
  const parts = h.split(" - ");
  return parts.length > 1 ? parts[1].trim() : "";
}

function isFooterRow(row) {
  return row.some((c) => typeof c === "string" && /generated by/i.test(c));
}

async function parseWorkbook(file) {
  const buf = await file.arrayBuffer();
  const wb = XLSX.read(buf, { type: "array" });
  const ws = wb.Sheets[wb.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json(ws, { header: 1, defval: null, blankrows: false });
  if (!rows.length) throw new Error("Empty sheet");
  const header = rows[0].map((h) => (h === null ? "" : String(h).trim()));
  const body = rows.slice(1).filter((r) => r && r.length && !isFooterRow(r) && r[0] !== null && r[1] !== null);

  if (header.includes("Created Time")) {
    // password-not-set report: Name, Email, Groups, Created Time
    const nameIdx = header.indexOf("Name");
    const emailIdx = header.indexOf("Email");
    const groupIdx = header.indexOf("Groups");
    const timeIdx = header.indexOf("Created Time");
    const entries = body.map((r) => ({
      name: r[nameIdx] ?? "",
      email: r[emailIdx] ?? "",
      groups: r[groupIdx] ?? "",
      createdTime: timeIdx >= 0 ? r[timeIdx] ?? "" : "",
    }));
    // File-level meta is only an approximation (first row's Groups value) used
    // for the upload-list chip label. Real section grouping happens later,
    // per entry, off each entry's own `groups` value.
    const meta = parseSectionMeta(entries[0]?.groups, file.name);
    return { kind: "password", fileName: file.name, meta, entries };
  }

  if (header.includes("Member Id") || header.includes("Groups")) {
    // group-wise course progress report
    const idIdx = header.indexOf("Member Id");
    const nameIdx = header.indexOf("Name");
    const emailIdx = header.indexOf("Email");
    const groupIdx = header.indexOf("Groups");
    const courseIdxs = header
      .map((h, i) => ({ h, i }))
      .filter(({ h, i }) => i > groupIdx && h && h !== "");
    const courses = courseIdxs.map(({ h }) => ({
      key: h,
      label: shortCourseLabel(h),
      code: courseCode(h),
    }));

    const students = body.map((r) => {
      const courseValues = {};
      let sum = 0;
      courseIdxs.forEach(({ h, i }) => {
        const { value, notStarted } = parseCell(r[i]);
        courseValues[h] = { value, notStarted };
        sum += value;
      });
      const avg = courseIdxs.length ? sum / courseIdxs.length : 0;
      return {
        id: idIdx >= 0 ? r[idIdx] : "",
        name: nameIdx >= 0 ? r[nameIdx] : "",
        email: emailIdx >= 0 ? r[emailIdx] : "",
        groups: groupIdx >= 0 ? r[groupIdx] : "",
        courseValues,
        avg,
      };
    });

    // Same story as above: file-level meta is only a display approximation.
    const meta = parseSectionMeta(students[0]?.groups, file.name);
    return { kind: "course", fileName: file.name, meta, courses, students };
  }

  throw new Error("Unrecognized report format — expected a 'group-wise course' or 'password-not-set' export.");
}

function fmtPct(n) {
  return `${n.toFixed(1)}%`;
}

// ---------- small UI atoms ----------
function StatCard({ icon: Icon, label, value, sub, accent }) {
  return (
    <div style={{
      background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4,
      padding: "18px 20px", flex: "1 1 160px", minWidth: 160,
      borderTop: `3px solid ${accent || GOLD}`,
    }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, color: SLATE, fontSize: 12, letterSpacing: 0.3 }}>
        <Icon size={14} />
        <span>{label}</span>
      </div>
      <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 30, color: NAVY, marginTop: 6, fontWeight: 600 }}>
        {value}
      </div>
      {sub && <div style={{ fontSize: 12, color: SLATE, marginTop: 2 }}>{sub}</div>}
    </div>
  );
}

function barColor(v) {
  if (v >= 70) return GREEN;
  if (v >= 40) return GOLD_SOFT;
  return RUST;
}

// Plain HTML/CSS horizontal bar rows — used instead of an SVG chart library so long
// course names wrap naturally onto multiple lines (no fixed-height axis to overlap)
// and the block grows to whatever height the content actually needs, on screen and in print.
function BarRows({ rows, labelWidth = 200 }) {
  return (
    <div>
      <div style={{ display: "flex", gap: 10, marginBottom: 8, paddingLeft: labelWidth + 10 }}>
        <div style={{ flex: 1, position: "relative", height: 14 }}>
          {[0, 25, 50, 75, 100].map((v) => (
            <span
              key={v}
              style={{
                position: "absolute", left: `${v}%`, fontSize: 10.5, color: SLATE,
                transform: v === 0 ? "none" : v === 100 ? "translateX(-100%)" : "translateX(-50%)",
              }}
            >
              {v}%
            </span>
          ))}
        </div>
        <div style={{ width: 52, flexShrink: 0 }} />
      </div>
      {rows.map((r, i) => (
        <div key={i} style={{ display: "flex", alignItems: "center", gap: 10, margin: "10px 0" }}>
          <div style={{
            width: labelWidth, flexShrink: 0, fontSize: 12.5, color: INK, textAlign: "right",
            paddingRight: 4, lineHeight: 1.35, wordBreak: "break-word",
          }}>
            {r.label}
          </div>
          <div style={{
            flex: 1, background: "#F1ECE0", borderRadius: 3, height: 18, position: "relative",
            overflow: "hidden",
            backgroundImage: "linear-gradient(to right, transparent 24.6%, #E0DACB 24.6%, #E0DACB 25.2%, transparent 25.2%, transparent 49.6%, #E0DACB 49.6%, #E0DACB 50.2%, transparent 50.2%, transparent 74.6%, #E0DACB 74.6%, #E0DACB 75.2%, transparent 75.2%)",
          }}>
            <div style={{ height: "100%", borderRadius: 3, width: `${Math.max(1.5, Math.min(100, r.value))}%`, background: r.color }} />
          </div>
          <div style={{ width: 52, flexShrink: 0, fontSize: 12.5, color: INK, fontWeight: 600 }}>
            {fmtPct(r.value)}
          </div>
        </div>
      ))}
    </div>
  );
}

export default function CourseInsightsApp() {
  const [courseFiles, setCourseFiles] = useState([]);
  const [passwordFiles, setPasswordFiles] = useState([]);
  const [busy, setBusy] = useState(false);
  const [generatingPdf, setGeneratingPdf] = useState(false);
  const [pdfError, setPdfError] = useState("");
  const [pdfProgress, setPdfProgress] = useState({ done: 0, total: 0 });
  const [fileErrors, setFileErrors] = useState([]);
  const [threshold, setThreshold] = useState(40); // At Risk / Average boundary
  const [avgMax, setAvgMax] = useState(70); // Average / Good boundary
  const [goodMax, setGoodMax] = useState(90); // Good / Excellent boundary
  const [collegeName, setCollegeName] = useState("");
  const [collegeLogo, setCollegeLogo] = useState(""); // data URL, embeds directly so the exported HTML has no external file dependency
  const [dragOver, setDragOver] = useState(false);
  const [expandedSections, setExpandedSections] = useState({});
  const inputRef = useRef(null);
  const logoInputRef = useRef(null);
  const reportRef = useRef(null);

  const handleLogoFile = useCallback((file) => {
    if (!file) return;
    if (!/^image\//.test(file.type)) return;
    const reader = new FileReader();
    reader.onload = () => setCollegeLogo(reader.result);
    reader.readAsDataURL(file);
  }, []);

  const handleFiles = useCallback(async (fileList) => {
    setBusy(true);
    const newErrors = [];
    const newCourse = [];
    const newPassword = [];
    for (const file of Array.from(fileList)) {
      if (!/\.xlsx?$/i.test(file.name)) {
        newErrors.push(`${file.name}: not an Excel file, skipped.`);
        continue;
      }
      try {
        const parsed = await parseWorkbook(file);
        if (parsed.kind === "course") newCourse.push(parsed);
        else newPassword.push(parsed);
      } catch (e) {
        newErrors.push(`${file.name}: ${e.message || "could not be read"}`);
      }
    }
    setCourseFiles((prev) => {
      const map = new Map(prev.map((f) => [f.fileName, f]));
      newCourse.forEach((f) => map.set(f.fileName, f));
      return Array.from(map.values());
    });
    setPasswordFiles((prev) => {
      const map = new Map(prev.map((f) => [f.fileName, f]));
      newPassword.forEach((f) => map.set(f.fileName, f));
      return Array.from(map.values());
    });
    setFileErrors(newErrors);
    setBusy(false);
  }, []);

  const onDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    if (e.dataTransfer.files?.length) handleFiles(e.dataTransfer.files);
  };

  const removeCourseFile = (name) => setCourseFiles((p) => p.filter((f) => f.fileName !== name));
  const removePasswordFile = (name) => setPasswordFiles((p) => p.filter((f) => f.fileName !== name));
  const clearAll = () => { setCourseFiles([]); setPasswordFiles([]); setFileErrors([]); };

  // ---------- aggregation ----------
  const insights = useMemo(() => {
    if (!courseFiles.length) return null;

    // Group every student by their own "Groups" cell value — not by which
    // file they came from. This is what makes a single combined workbook
    // (many sections stacked in one sheet) split apart into the right
    // sections, while multiple individual per-section files that happen to
    // share a Groups value still merge together correctly.
    const sectionMap = new Map();
    courseFiles.forEach((f) => {
      f.students.forEach((st) => {
        const rawGroup = (st.groups && String(st.groups).trim()) || "";
        const meta = parseSectionMeta(rawGroup, f.fileName);
        const key = meta.label;
        if (!sectionMap.has(key)) {
          sectionMap.set(key, { ...meta, fileNames: new Set(), courseMap: new Map(), students: [] });
        }
        const entry = sectionMap.get(key);
        entry.fileNames.add(f.fileName);
        f.courses.forEach((c) => { if (!entry.courseMap.has(c.key)) entry.courseMap.set(c.key, c); });
        entry.students.push(st);
      });
    });

    const sections = Array.from(sectionMap.values())
      .map((sec) => {
        const courses = Array.from(sec.courseMap.values());
        const studentCount = sec.students.length;
        const avgOfAvgs = studentCount ? sec.students.reduce((s, st) => s + st.avg, 0) / studentCount : 0;
        const perCourse = courses.map((c) => {
          let sum = 0, notStartedCount = 0, completeCount = 0, seen = 0;
          sec.students.forEach((st) => {
            const cv = st.courseValues[c.key];
            if (!cv) return; // this student's source file didn't include this course column
            seen++;
            sum += cv.value;
            if (cv.notStarted) notStartedCount++;
            if (cv.value >= COMPLETE_THRESHOLD) completeCount++;
          });
          return {
            ...c,
            avg: seen ? sum / seen : 0,
            notStartedCount,
            completeCount,
            notStartedRate: seen ? notStartedCount / seen : 0,
          };
        });
        const atRisk = sec.students.filter((s) => s.avg < threshold);
        const startedCount = sec.students.filter((s) => Object.values(s.courseValues).some((cv) => !cv.notStarted)).length;
        const notStartedCount = studentCount - startedCount;
        return {
          batch: sec.batch, branch: sec.branch, section: sec.section, label: sec.label,
          fileName: Array.from(sec.fileNames).join(", "),
          studentCount, avgOfAvgs, perCourse, atRisk, startedCount, notStartedCount,
          students: sec.students, courses,
        };
      })
      .sort((a, b) => a.label.localeCompare(b.label));

    const totalStudents = sections.reduce((s, sec) => s + sec.studentCount, 0);
    const overallAvg = totalStudents
      ? sections.reduce((s, sec) => s + sec.avgOfAvgs * sec.studentCount, 0) / totalStudents
      : 0;
    const totalAtRisk = sections.reduce((s, sec) => s + sec.atRisk.length, 0);

    // password issues joined to sections — grouped the same way, by each
    // entry's own Groups value, so a combined password export splits apart
    // just like the combined course export does.
    const pwBySection = {};
    passwordFiles.forEach((f) => {
      f.entries.forEach((entry) => {
        const rawGroup = (entry.groups && String(entry.groups).trim()) || "";
        const meta = parseSectionMeta(rawGroup, f.fileName);
        const key = meta.label;
        if (!pwBySection[key]) pwBySection[key] = { meta, entries: [] };
        pwBySection[key].entries.push(entry);
      });
    });
    const totalPasswordIssues = Object.values(pwBySection).reduce((s, g) => s + g.entries.length, 0);

    // enrollment/activation summary table (mirrors the CodeTantra group dashboard view)
    const enrollment = sections.map((sec) => {
      const passwordNotSet = pwBySection[sec.label]?.entries.length || 0;
      return {
        label: sec.label,
        started: sec.startedCount,
        notStarted: sec.notStartedCount,
        passwordNotSet,
        subTotal: sec.studentCount + passwordNotSet,
      };
    });
    const enrollmentTotals = enrollment.reduce((acc, r) => ({
      started: acc.started + r.started,
      notStarted: acc.notStarted + r.notStarted,
      passwordNotSet: acc.passwordNotSet + r.passwordNotSet,
      subTotal: acc.subTotal + r.subTotal,
    }), { started: 0, notStarted: 0, passwordNotSet: 0, subTotal: 0 });

    // branch grouping for course comparison charts
    const branches = {};
    sections.forEach((sec) => {
      if (!branches[sec.branch]) branches[sec.branch] = { sections: [], courseAgg: new Map() };
      branches[sec.branch].sections.push(sec);
      sec.perCourse.forEach((c) => {
        const agg = branches[sec.branch].courseAgg.get(c.key) || {
          label: c.label, code: c.code, sumPct: 0, students: 0, notStarted: 0,
        };
        agg.sumPct += c.avg * sec.studentCount;
        agg.students += sec.studentCount;
        agg.notStarted += c.notStartedCount;
        branches[sec.branch].courseAgg.set(c.key, agg);
      });
    });
    const branchCharts = Object.entries(branches).map(([branch, data]) => ({
      branch,
      courses: Array.from(data.courseAgg.values()).map((c) => ({
        ...c,
        avg: c.students ? c.sumPct / c.students : 0,
        notStartedRate: c.students ? c.notStarted / c.students : 0,
      })),
    }));

    // Every student, flattened across all sections, with section label and
    // not-started course list attached — the base list the performance
    // categories below are filtered from.
    const allStudentsFlat = sections.flatMap((sec) => sec.students.map((s) => ({
      ...s,
      sectionLabel: sec.label,
      notStartedCourses: sec.courses
        .filter((c) => s.courseValues[c.key] && s.courseValues[c.key].notStarted)
        .map((c) => c.label),
    })));

    // Full-picture performance bands: everyone is shown, not just the
    // at-risk group, so the report covers at-risk / average / good /
    // excellent completion. Boundaries are user-configurable (threshold,
    // avgMax, goodMax) rather than fixed, since what counts as "good"
    // varies by cohort, course difficulty, and how far into the term it is.
    // Guard against the boundaries being dragged out of order so the bands
    // never invert into an impossible range.
    const b1 = threshold;
    const b2 = Math.max(avgMax, b1);
    const b3 = Math.max(goodMax, b2);
    const categoryDefs = [
      { key: "atRisk", title: "At Risk", range: `below ${b1}%`, color: RUST, test: (avg) => avg < b1 },
      { key: "average", title: "Average", range: `${b1}%–${(b2 - 0.1).toFixed(1)}%`, color: GOLD, test: (avg) => avg >= b1 && avg < b2 },
      { key: "good", title: "Good", range: `${b2}%–${(b3 - 0.1).toFixed(1)}%`, color: NAVY_SOFT, test: (avg) => avg >= b2 && avg < b3 },
      { key: "excellent", title: "Excellent", range: `${b3}% and above`, color: GREEN, test: (avg) => avg >= b3 },
    ];
    const categorizedStudents = categoryDefs.map((c) => ({
      ...c,
      students: allStudentsFlat.filter((s) => c.test(s.avg)).sort((a, b) => a.avg - b.avg),
    }));
    const atRiskAll = categorizedStudents[0].students;

    const topPerformers = [...allStudentsFlat].sort((a, b) => b.avg - a.avg).slice(0, 5);

    const sortedByAvg = [...sections].sort((a, b) => a.avgOfAvgs - b.avgOfAvgs);
    const weakestSection = sortedByAvg[0];
    const strongestSection = sortedByAvg[sortedByAvg.length - 1];

    let weakestCourse = null;
    branchCharts.forEach((b) => {
      b.courses.forEach((c) => {
        if (!weakestCourse || c.notStartedRate > weakestCourse.notStartedRate) {
          weakestCourse = { ...c, branch: b.branch };
        }
      });
    });

    const batches = Array.from(new Set(sections.map((s) => s.batch))).filter((b) => b !== "—");

    return {
      sections, totalStudents, overallAvg, totalAtRisk, pwBySection, totalPasswordIssues,
      branchCharts, allStudentsFlat, categorizedStudents, atRiskAll, topPerformers,
      weakestSection, strongestSection, weakestCourse, batches, enrollment, enrollmentTotals,
    };
  }, [courseFiles, passwordFiles, threshold, avgMax, goodMax]);

  const generatedDate = new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });

  const toggleSection = (label) => setExpandedSections((p) => ({ ...p, [label]: !p[label] }));

  // Printing/exporting directly from inside this sandboxed preview is unreliable,
  // so instead we package the rendered report into a standalone HTML file the
  // person can open in a normal browser tab, where "Print / Save as PDF" always works.
  const downloadReport = () => {
    if (!reportRef.current) return;
    const contentHTML = reportRef.current.outerHTML;
    const cleanCollege = collegeName.trim();
    const escapedCollege = cleanCollege.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    const docTitle = cleanCollege ? `${escapedCollege} — Course Progress Report` : "Course Progress Report";
    const faviconHref = collegeLogo || "data:image/svg+xml," + encodeURIComponent(
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="18" fill="${NAVY}"/><text x="50" y="66" font-size="58" text-anchor="middle">🎓</text></svg>`
    );
    const doc = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<link rel="icon" href="${faviconHref}" />
<title>${docTitle}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@500;600;700&family=Inter:wght@400;500;600;700&display=swap');
  * { box-sizing: border-box; }
  * { -webkit-print-color-adjust: exact; print-color-adjust: exact; color-adjust: exact; }
  body { font-family: 'Inter', -apple-system, sans-serif; background: ${PAPER}; margin: 0; padding: 28px; color: ${INK}; }
  table.cip-table { width: 100%; border-collapse: collapse; font-size: 13px; }
  table.cip-table th { text-align: left; font-weight: 600; color: ${SLATE}; font-size: 11px;
    letter-spacing: 0.4px; text-transform: uppercase; padding: 8px 10px; border-bottom: 2px solid ${NAVY}; }
  table.cip-table td { padding: 8px 10px; border-bottom: 1px solid ${PAPER_LINE}; }
  table.cip-table tr:last-child td { border-bottom: none; }
  .print-bar { position: sticky; top: 0; display: flex; justify-content: flex-end; padding: 10px 0 18px; background: ${PAPER}; z-index: 10; }
  .print-btn { background: ${GOLD_SOFT}; color: ${NAVY}; font-weight: 600; font-size: 14px; border: none;
    padding: 10px 20px; border-radius: 4px; cursor: pointer; font-family: 'Inter', sans-serif; }
  /* Let cards flow and pack naturally onto pages — only keep a single card from
     splitting across a page boundary. No forced page-before, so the print engine
     fits as many cards as actually fit on each page based on real height. */
  .cip-card, .cip-chart-card { break-inside: avoid; -webkit-column-break-inside: avoid; page-break-inside: avoid; }
  table.cip-table tr { break-inside: avoid; page-break-inside: avoid; }
  @media print {
    .print-bar { display: none; }
    .print-bar-hint { display: none; }
    body { padding: 0; background: #fff; }
    * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; color-adjust: exact !important; }
  }
</style>
</head>
<body>
  <div class="print-bar"><button class="print-btn" onclick="window.print()">Print / Save as PDF</button></div>
  <div style="font-size: 12px; color: ${SLATE}; text-align: right; margin-top: -8px;" class="print-bar-hint">
    Tip: in the print dialog — turn <strong>"Background graphics"</strong> ON (so bars/shading show up) and
    <strong>"Headers and footers"</strong> OFF (so the browser doesn't add its own date/time and file path to each page).
  </div>
  ${contentHTML}
</body>
</html>`;
    const blob = new Blob([doc], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const slug = reportFileSlug();
    a.download = slug ? `${slug}-course-progress-report.html` : "course-progress-report.html";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const reportFileSlug = () => {
    const clean = collegeName.trim();
    return clean ? clean.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") : "";
  };

  // Direct-to-PDF export: snapshots each marked report chunk ([data-pdf-block])
  // as an image via html2canvas, then packs those images onto A4 pages with
  // jsPDF — same "fit as many blocks as fit, only break when a block doesn't
  // fit" logic as the print stylesheet, but producing real PDF bytes so
  // there's no print dialog step. A block taller than a page (a long table)
  // is sliced across pages so nothing gets cut off.
  //
  // Large reports were triggering the browser's "Page Unresponsive" warning
  // because html2canvas does heavy synchronous rasterization work; running
  // many of those back-to-back with no gap blocks the main thread long enough
  // to trip Chrome's watchdog. Two things fix that: (1) yielding to the event
  // loop between every block via a 0ms timeout, which resets the watchdog and
  // lets the UI repaint, and (2) breaking big chunks like the password-not-set
  // list into one block per section instead of one giant block.
  const yieldToBrowser = () => new Promise((resolve) => setTimeout(resolve, 0));

  const downloadPdf = async () => {
    if (!reportRef.current) return;
    setGeneratingPdf(true);
    setPdfError("");
    setPdfProgress({ done: 0, total: 0 });
    await yieldToBrowser(); // let the "Generating PDF…" button state paint before heavy work starts

    try {
      const pageWidthMm = 210; // A4
      const pageHeightMm = 297;
      const marginMm = 10;
      const usableWidthMm = pageWidthMm - marginMm * 2;
      const usableHeightMm = pageHeightMm - marginMm * 2;
      const gapMm = 4;

      const pdf = new jsPDF({ unit: "mm", format: "a4", compress: true });
      let cursorY = marginMm;
      let firstBlock = true;

      const blocks = Array.from(reportRef.current.querySelectorAll('[data-pdf-block="true"]')).filter(
        (el) => el.offsetHeight > 0
      );
      setPdfProgress({ done: 0, total: blocks.length });

      for (let i = 0; i < blocks.length; i++) {
        const el = blocks[i];
        const canvas = await html2canvas(el, {
          scale: 1.5,
          backgroundColor: "#ffffff",
          useCORS: true,
          logging: false,
        });

        const pxPerMm = canvas.width / usableWidthMm;
        const usableHeightPx = usableHeightMm * pxPerMm;
        const totalHeightPx = canvas.height;
        let renderedPx = 0;

        while (renderedPx < totalHeightPx) {
          const sliceHeightPx = Math.min(usableHeightPx, totalHeightPx - renderedPx);
          const sliceHeightMm = sliceHeightPx / pxPerMm;

          // move to a fresh page if this slice won't fit in the remaining space
          if (!firstBlock && cursorY + sliceHeightMm > pageHeightMm - marginMm && cursorY > marginMm) {
            pdf.addPage();
            cursorY = marginMm;
          }
          if (renderedPx > 0 && cursorY !== marginMm) {
            // a slice that's a continuation of an oversized block always starts a fresh page
            pdf.addPage();
            cursorY = marginMm;
          }

          const sliceCanvas = document.createElement("canvas");
          sliceCanvas.width = canvas.width;
          sliceCanvas.height = sliceHeightPx;
          sliceCanvas.getContext("2d").drawImage(
            canvas, 0, renderedPx, canvas.width, sliceHeightPx, 0, 0, canvas.width, sliceHeightPx
          );
          const sliceData = sliceCanvas.toDataURL("image/png");
          pdf.addImage(sliceData, "PNG", marginMm, cursorY, usableWidthMm, sliceHeightMm);

          cursorY += sliceHeightMm;
          renderedPx += sliceHeightPx;
          firstBlock = false;
        }
        cursorY += gapMm;

        setPdfProgress({ done: i + 1, total: blocks.length });
        await yieldToBrowser(); // give the browser a chance to paint/respond before the next heavy capture
      }

      const slug = reportFileSlug();
      pdf.save(slug ? `${slug}-course-progress-report.pdf` : "course-progress-report.pdf");
    } catch (err) {
      console.error(err);
      setPdfError("Couldn't generate the PDF in this browser. Try the HTML download and print it instead.");
    } finally {
      setGeneratingPdf(false);
    }
  };

  return (
    <div style={{
      fontFamily: "'Inter', -apple-system, sans-serif", background: PAPER, minHeight: "100vh",
      color: INK, paddingBottom: 60,
    }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@500;600;700&family=Inter:wght@400;500;600;700&display=swap');
        * { box-sizing: border-box; }
        .cip-btn { cursor: pointer; border: none; font-family: inherit; }
        .cip-btn:disabled { opacity: 0.5; cursor: not-allowed; }
        table.cip-table { width: 100%; border-collapse: collapse; font-size: 13px; }
        table.cip-table th { text-align: left; font-weight: 600; color: ${SLATE}; font-size: 11px;
          letter-spacing: 0.4px; text-transform: uppercase; padding: 8px 10px; border-bottom: 2px solid ${NAVY}; }
        table.cip-table td { padding: 8px 10px; border-bottom: 1px solid ${PAPER_LINE}; }
        table.cip-table tr:last-child td { border-bottom: none; }
        @media print {
          .no-print { display: none !important; }
          body, .cip-root { background: #fff !important; }
          .cip-page { box-shadow: none !important; margin: 0 !important; padding: 0 !important; max-width: none !important; }
          .cip-card, .cip-chart-card { break-inside: avoid; page-break-inside: avoid; }
          table.cip-table tr { break-inside: avoid; page-break-inside: avoid; }
          * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; color-adjust: exact !important; }
        }
      `}</style>

      {/* ---------- Upload / control zone (no-print) ---------- */}
      <div className="no-print" style={{ background: NAVY, padding: "28px 32px 24px" }}>
        <div style={{ maxWidth: 1080, margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 4 }}>
            <GraduationCap size={22} color={GOLD_SOFT} />
            <span style={{ color: "#fff", fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 20, fontWeight: 600 }}>
              Course Progress Insights
            </span>
          </div>
          <div style={{ color: "#B8C0D4", fontSize: 13, marginBottom: 18 }}>
            Upload section-wise CodeTantra course reports — individual per-section files, or one combined workbook
            with every section stacked together — to generate a single consolidated report for your SPOC. Sections
            are always read from each row's "Groups" column.
          </div>

          <div style={{ display: "flex", gap: 20, flexWrap: "wrap", marginBottom: 18 }}>
            <label style={{ display: "block", flex: "1 1 320px" }}>
              <div style={{ color: "#B8C0D4", fontSize: 12.5, marginBottom: 5 }}>College / Institute name (shown on the report)</div>
              <input
                type="text"
                value={collegeName}
                onChange={(e) => setCollegeName(e.target.value)}
                placeholder="e.g. Sreenidhi Institute of Science and Technology"
                style={{
                  width: "100%", maxWidth: 420, padding: "8px 10px", borderRadius: 4,
                  border: "1px solid #3E5079", background: "#152038", color: "#fff", fontSize: 13.5,
                }}
              />
            </label>

            <div style={{ flex: "0 0 auto" }}>
              <div style={{ color: "#B8C0D4", fontSize: 12.5, marginBottom: 5 }}>College logo (optional)</div>
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                {collegeLogo && (
                  <img
                    src={collegeLogo} alt="College logo preview"
                    style={{ height: 34, maxWidth: 90, objectFit: "contain", background: "#fff", borderRadius: 3, padding: 2 }}
                  />
                )}
                <button
                  type="button"
                  className="cip-btn"
                  onClick={() => logoInputRef.current?.click()}
                  style={{
                    background: "rgba(255,255,255,0.06)", color: "#fff", fontSize: 12.5,
                    border: "1px solid #3E5079", borderRadius: 4, padding: "7px 12px",
                  }}
                >
                  {collegeLogo ? "Change logo" : "Upload logo"}
                </button>
                {collegeLogo && (
                  <X
                    size={16}
                    style={{ cursor: "pointer", color: "#8B96B2" }}
                    onClick={() => setCollegeLogo("")}
                  />
                )}
                <input
                  ref={logoInputRef} type="file" accept="image/*"
                  style={{ display: "none" }}
                  onChange={(e) => handleLogoFile(e.target.files?.[0])}
                />
              </div>
            </div>
          </div>

          <div
            onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
            onDragLeave={() => setDragOver(false)}
            onDrop={onDrop}
            onClick={() => inputRef.current?.click()}
            style={{
              border: `2px dashed ${dragOver ? GOLD_SOFT : "#3E5079"}`, borderRadius: 6,
              padding: "22px 20px", textAlign: "center", cursor: "pointer",
              background: dragOver ? "rgba(217,169,58,0.08)" : "rgba(255,255,255,0.03)",
              transition: "all 0.15s",
            }}
          >
            <UploadCloud size={26} color={GOLD_SOFT} style={{ marginBottom: 6 }} />
            <div style={{ color: "#fff", fontSize: 14, fontWeight: 500 }}>
              {busy ? "Reading files…" : "Drop .xlsx files here, or click to browse"}
            </div>
            <div style={{ color: "#8B96B2", fontSize: 12, marginTop: 3 }}>
              Group-wise course reports and password-not-set reports — individual sections or one combined sheet, any number at once
            </div>
            <input
              ref={inputRef} type="file" multiple accept=".xlsx,.xls"
              style={{ display: "none" }}
              onChange={(e) => e.target.files?.length && handleFiles(e.target.files)}
            />
          </div>

          {fileErrors.length > 0 && (
            <div style={{ marginTop: 12, background: "rgba(168,69,47,0.15)", border: `1px solid ${RUST}`, borderRadius: 4, padding: "10px 14px" }}>
              {fileErrors.map((e, i) => (
                <div key={i} style={{ color: "#F3C9BE", fontSize: 12.5, display: "flex", gap: 6, alignItems: "flex-start" }}>
                  <AlertTriangle size={13} style={{ marginTop: 2, flexShrink: 0 }} /> {e}
                </div>
              ))}
            </div>
          )}

          {(courseFiles.length > 0 || passwordFiles.length > 0) && (
            <div style={{ marginTop: 16, display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" }}>
              {courseFiles.map((f) => {
                const distinctGroups = new Set(
                  f.students.map((s) => (s.groups && String(s.groups).trim()) || "Unspecified")
                ).size;
                return (
                  <span key={f.fileName} style={{
                    display: "inline-flex", alignItems: "center", gap: 6, background: "#233A63",
                    color: "#fff", fontSize: 12, padding: "5px 6px 5px 10px", borderRadius: 20,
                  }}>
                    <FileSpreadsheet size={12} color={GOLD_SOFT} />
                    {f.fileName}{" "}
                    <span style={{ color: "#8B96B2" }}>
                      · {f.students.length} students{distinctGroups > 1 ? ` · ${distinctGroups} sections` : ""}
                    </span>
                    <X size={13} style={{ cursor: "pointer", marginLeft: 2 }} onClick={() => removeCourseFile(f.fileName)} />
                  </span>
                );
              })}
              {passwordFiles.map((f) => {
                const distinctGroups = new Set(
                  f.entries.map((e) => (e.groups && String(e.groups).trim()) || "Unspecified")
                ).size;
                return (
                  <span key={f.fileName} style={{
                    display: "inline-flex", alignItems: "center", gap: 6, background: "#5A3E1B",
                    color: "#fff", fontSize: 12, padding: "5px 6px 5px 10px", borderRadius: 20,
                  }}>
                    <KeyRound size={12} color={GOLD_SOFT} />
                    {f.fileName}{" "}
                    <span style={{ color: "#C8B499" }}>
                      · {f.entries.length} no password{distinctGroups > 1 ? ` · ${distinctGroups} sections` : ""}
                    </span>
                    <X size={13} style={{ cursor: "pointer", marginLeft: 2 }} onClick={() => removePasswordFile(f.fileName)} />
                  </span>
                );
              })}
              <button className="cip-btn" onClick={clearAll} style={{
                background: "none", color: "#8B96B2", fontSize: 12, textDecoration: "underline", padding: "4px 6px",
              }}>
                clear all
              </button>
            </div>
          )}

          {insights && (
            <div style={{ marginTop: 18, display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}>
                <label style={{ color: "#B8C0D4", fontSize: 12.5, display: "flex", alignItems: "center", gap: 8 }}>
                  At-risk threshold (average % below)
                  <input
                    type="number" min={0} max={100} value={threshold}
                    onChange={(e) => setThreshold(Number(e.target.value) || 0)}
                    style={{ width: 56, padding: "4px 6px", borderRadius: 4, border: "1px solid #3E5079", background: "#152038", color: "#fff" }}
                  />
                </label>
                <label style={{ color: "#B8C0D4", fontSize: 12.5, display: "flex", alignItems: "center", gap: 8 }}>
                  Average performance threshold (average % from)
                  <input
                    type="number" min={0} max={100} value={threshold}
                    onChange={(e) => setThreshold(Number(e.target.value) || 0)}
                    style={{ width: 56, padding: "4px 6px", borderRadius: 4, border: "1px solid #3E5079", background: "#152038", color: "#fff" }}
                  />
                </label>
                <label style={{ color: "#B8C0D4", fontSize: 12.5, display: "flex", alignItems: "center", gap: 8 }}>
                  Good performance threshold (average % from)
                  <input
                    type="number" min={0} max={100} value={avgMax}
                    onChange={(e) => setAvgMax(Number(e.target.value) || 0)}
                    style={{ width: 56, padding: "4px 6px", borderRadius: 4, border: "1px solid #3E5079", background: "#152038", color: "#fff" }}
                  />
                </label>
                <label style={{ color: "#B8C0D4", fontSize: 12.5, display: "flex", alignItems: "center", gap: 8 }}>
                  Excellent performance threshold (average % from)
                  <input
                    type="number" min={0} max={100} value={goodMax}
                    onChange={(e) => setGoodMax(Number(e.target.value) || 0)}
                    style={{ width: 56, padding: "4px 6px", borderRadius: 4, border: "1px solid #3E5079", background: "#152038", color: "#fff" }}
                  />
                </label>
              </div>
              <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 10 }}>
                <button
                  className="cip-btn"
                  onClick={downloadReport}
                  style={{
                    display: "inline-flex", alignItems: "center", gap: 6,
                    background: "none", color: "#B8C0D4", fontSize: 12.5,
                    padding: "9px 4px", textDecoration: "underline",
                  }}
                >
                  Download as HTML instead
                </button>
                <button
                  className="cip-btn"
                  onClick={downloadPdf}
                  disabled={generatingPdf}
                  style={{
                    display: "inline-flex", alignItems: "center", gap: 8,
                    background: GOLD_SOFT, color: NAVY, fontWeight: 600, fontSize: 13.5,
                    padding: "9px 18px", borderRadius: 4,
                  }}
                >
                  <Download size={15} />
                  {generatingPdf
                    ? pdfProgress.total > 0
                      ? `Generating PDF… (${pdfProgress.done}/${pdfProgress.total})`
                      : "Generating PDF…"
                    : "Download PDF report"}
                </button>
              </div>
              {pdfError && (
                <div style={{ width: "100%", color: "#F3C9BE", fontSize: 12.5, display: "flex", gap: 6, alignItems: "flex-start" }}>
                  <AlertTriangle size={13} style={{ marginTop: 2, flexShrink: 0 }} /> {pdfError}
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* ---------- Report ---------- */}
      {!insights && (
        <div style={{ maxWidth: 640, margin: "60px auto", textAlign: "center", color: SLATE }}>
          <FileSpreadsheet size={36} color={PAPER_LINE} style={{ marginBottom: 10 }} />
          <div style={{ fontSize: 14 }}>
            Upload at least one group-wise course report to build the insights report.
            Every section is read automatically from the "Groups" column on each row — whether that's
            one file per section or a single combined workbook with all sections together.
          </div>
        </div>
      )}

      {insights && (
        <div ref={reportRef} className="cip-page" style={{ maxWidth: 1080, margin: "28px auto 0", padding: "0 32px" }}>

          {/* report header */}
          <div data-pdf-block="true" style={{ display: "flex", alignItems: "center", gap: 16, borderBottom: `3px solid ${NAVY}`, paddingBottom: 14, marginBottom: 22 }}>
            {collegeLogo && (
              <img
                src={collegeLogo} alt="College logo"
                style={{ height: 52, maxWidth: 100, objectFit: "contain", flexShrink: 0 }}
              />
            )}
            <div style={{ flex: 1, minWidth: 0 }}>
              {collegeName.trim() && (
                <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 15, fontWeight: 600, color: GOLD, letterSpacing: 0.3, marginBottom: 4, textTransform: "uppercase" }}>
                  {collegeName.trim()}
                </div>
              )}
              <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 26, fontWeight: 700, color: NAVY }}>
                Course Progress Report{insights.batches.length ? ` — ${insights.batches.join(", ")} Batch` : ""}
              </div>
              <div style={{ fontSize: 12.5, color: SLATE, marginTop: 4 }}>
                Generated {generatedDate} · {insights.sections.length} section{insights.sections.length !== 1 ? "s" : ""} ·
                {" "}{insights.totalStudents} students · at-risk cutoff: below {threshold}% average
              </div>
            </div>
          </div>

          {/* summary cards */}
          <div data-pdf-block="true" style={{ display: "flex", gap: 14, flexWrap: "wrap", marginBottom: 26 }} className="cip-card">
            <StatCard icon={Users} label="Total Students" value={insights.totalStudents} accent={NAVY} />
            <StatCard icon={GraduationCap} label="Sections Covered" value={insights.sections.length} accent={NAVY} />
            <StatCard icon={TrendingUp} label="Overall Avg. Completion" value={fmtPct(insights.overallAvg)} accent={barColor(insights.overallAvg)} />
            <StatCard icon={AlertTriangle} label={`At Risk (< ${threshold}%)`} value={insights.totalAtRisk} sub={`${((insights.totalAtRisk / insights.totalStudents) * 100 || 0).toFixed(1)}% of students`} accent={RUST} />
            <StatCard
              icon={TrendingUp}
              label="Excellent (90%+)"
              value={insights.categorizedStudents.find((c) => c.key === "excellent")?.students.length || 0}
              accent={GREEN}
            />
            <StatCard icon={KeyRound} label="Passwords Not Set" value={insights.totalPasswordIssues} accent={GOLD} />
          </div>

          {/* key observations */}
          <div data-pdf-block="true" className="cip-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 26 }}>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY, marginBottom: 10 }}>
              Key Observations
            </div>
            <ul style={{ margin: 0, paddingLeft: 18, fontSize: 13.5, lineHeight: 1.85, color: INK }}>
              {insights.strongestSection && insights.weakestSection && insights.sections.length > 1 && (
                <li>
                  <strong>{insights.strongestSection.label}</strong> leads with {fmtPct(insights.strongestSection.avgOfAvgs)} average
                  completion, while <strong>{insights.weakestSection.label}</strong> trails at {fmtPct(insights.weakestSection.avgOfAvgs)} —
                  a gap of {fmtPct(insights.strongestSection.avgOfAvgs - insights.weakestSection.avgOfAvgs)}.
                </li>
              )}
              {insights.weakestCourse && (
                <li>
                  <strong>{insights.weakestCourse.label}</strong>{insights.weakestCourse.code ? ` (${insights.weakestCourse.code})` : ""} has the
                  highest not-started rate in {insights.weakestCourse.branch}, with {(insights.weakestCourse.notStartedRate * 100).toFixed(0)}% of
                  students yet to begin.
                </li>
              )}
              <li>
                <strong>{insights.totalAtRisk}</strong> student{insights.totalAtRisk !== 1 ? "s" : ""} ({((insights.totalAtRisk / insights.totalStudents) * 100 || 0).toFixed(1)}%
                of those covered) have an average completion below the {threshold}% threshold and may need follow-up.
              </li>
              {insights.totalPasswordIssues > 0 && (
                <li>
                  <strong>{insights.totalPasswordIssues}</strong> student{insights.totalPasswordIssues !== 1 ? "s" : ""} across
                  {" "}{Object.keys(insights.pwBySection).length} section{Object.keys(insights.pwBySection).length !== 1 ? "s" : ""} have
                  not set a CodeTantra password yet and likely have no recorded progress at all — flagged separately below.
                </li>
              )}
            </ul>
          </div>

          {/* enrollment / activation summary — mirrors the source dashboard's group table */}
          <div data-pdf-block="true" className="cip-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 26 }}>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY, marginBottom: 4 }}>
              Enrollment &amp; Activation Summary
            </div>
            <div style={{ fontSize: 12, color: SLATE, marginBottom: 10 }}>
              Started = has begun at least one course · Not Started = account active, zero progress on every course · Password Not Set = never logged in
            </div>
            <table className="cip-table">
              <thead>
                <tr>
                  <th>Group</th>
                  <th>Started ({insights.enrollmentTotals.started})</th>
                  <th>Not Started ({insights.enrollmentTotals.notStarted})</th>
                  <th>Password Not Set ({insights.enrollmentTotals.passwordNotSet})</th>
                  <th>Sub Total ({insights.enrollmentTotals.subTotal})</th>
                </tr>
              </thead>
              <tbody>
                {insights.enrollment.map((r) => (
                  <tr key={r.label}>
                    <td>
                      <span style={{
                        display: "inline-block", fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 12.5,
                        color: NAVY_SOFT, background: "#EAF3F8", border: `1px solid #C7DFEA`, borderRadius: 4,
                        padding: "2px 8px",
                      }}>
                        {r.label}
                      </span>
                    </td>
                    <td style={{ color: r.started > 0 ? NAVY_SOFT : INK, fontWeight: 600 }}>{r.started}</td>
                    <td style={{ color: r.notStarted > 0 ? RUST : INK, fontWeight: r.notStarted > 0 ? 600 : 400 }}>{r.notStarted}</td>
                    <td style={{ color: r.passwordNotSet > 0 ? GOLD : INK, fontWeight: r.passwordNotSet > 0 ? 600 : 400 }}>{r.passwordNotSet}</td>
                    <td style={{ fontWeight: 600 }}>{r.subTotal}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr style={{ borderTop: `2px solid ${NAVY}` }}>
                  <td style={{ fontWeight: 700, color: NAVY }}>Total</td>
                  <td style={{ fontWeight: 700 }}>{insights.enrollmentTotals.started}</td>
                  <td style={{ fontWeight: 700 }}>{insights.enrollmentTotals.notStarted}</td>
                  <td style={{ fontWeight: 700 }}>{insights.enrollmentTotals.passwordNotSet}</td>
                  <td style={{ fontWeight: 700 }}>{insights.enrollmentTotals.subTotal}</td>
                </tr>
              </tfoot>
            </table>
          </div>

          {/* section-wise chart — flows with the rest of the report; the print
              engine only pushes it to a new page if it doesn't fit on the current
              one (see .cip-chart-card rule in the stylesheet below) */}
          <div data-pdf-block="true" className="cip-card cip-chart-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 16 }}>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY, marginBottom: 4 }}>
              Average Completion by Section
            </div>
            <div style={{ fontSize: 12, color: SLATE, marginBottom: 14 }}>Mean of each student's average across all enabled courses</div>
            <BarRows
              rows={insights.sections.map((s) => ({ label: s.label, value: s.avgOfAvgs, color: barColor(s.avgOfAvgs) }))}
              labelWidth={130}
            />
          </div>

          {/* course-wise chart per section — packed onto pages by the print engine
              based on each card's actual measured height, instead of always
              starting a fresh page (which left huge blank gaps below short charts) */}
          {insights.sections.map((sec) => (
            <div
              key={sec.label}
              data-pdf-block="true"
              className="cip-card cip-chart-card"
              style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 16 }}
            >
              <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY, marginBottom: 4 }}>
                Course-wise Average Completion — {sec.label}
              </div>
              <div style={{ fontSize: 12, color: SLATE, marginBottom: 14 }}>{sec.studentCount} students in this section</div>
              <BarRows
                rows={sec.perCourse.map((c) => ({ label: c.label, value: c.avg, color: barColor(c.avg) }))}
                labelWidth={260}
              />
            </div>
          ))}

          {/* section detail table */}
          <div data-pdf-block="true" className="cip-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 26 }}>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY, marginBottom: 10 }}>
              Section Summary
            </div>
            <table className="cip-table">
              <thead>
                <tr>
                  <th>Section</th><th>Students</th><th>Avg. Completion</th><th>At Risk</th><th>Passwords Not Set</th>
                </tr>
              </thead>
              <tbody>
                {insights.sections.map((s) => (
                  <tr key={s.label}>
                    <td style={{ fontWeight: 600, color: NAVY }}>{s.label}</td>
                    <td>{s.studentCount}</td>
                    <td><span style={{ color: barColor(s.avgOfAvgs), fontWeight: 600 }}>{fmtPct(s.avgOfAvgs)}</span></td>
                    <td>{s.atRisk.length}</td>
                    <td>{insights.pwBySection[s.label]?.entries.length || 0}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* student performance — everyone is shown, grouped into
              at-risk / average / good / excellent completion bands, each
              independently collapsible on screen (always fully rendered
              for print/PDF export) */}
          <div data-pdf-block="true" className="cip-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 8 }}>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY }}>
              Student Performance
            </div>
            <div style={{ fontSize: 12, color: SLATE, marginTop: 4 }}>
              All {insights.totalStudents} students, grouped by average completion band
            </div>
          </div>

          {insights.categorizedStudents.map((cat) => {
            const stateKey = `perf-${cat.key}`;
            const isOpen = expandedSections[stateKey] !== false;
            return (
              <div
                key={cat.key}
                data-pdf-block="true"
                className="cip-card"
                style={{
                  background: "#fff", border: `1px solid ${PAPER_LINE}`, borderLeft: `4px solid ${cat.color}`,
                  borderRadius: 4, padding: "14px 22px", marginBottom: 10,
                }}
              >
                <div
                  onClick={() => toggleSection(stateKey)}
                  style={{ display: "flex", alignItems: "center", gap: 6, cursor: "pointer", fontWeight: 600, color: NAVY, fontSize: 13.5, marginBottom: 6 }}
                  className="no-print"
                >
                  {isOpen ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                  {cat.title} <span style={{ fontWeight: 400, color: SLATE }}>({cat.range})</span>
                  <span style={{ marginLeft: "auto", color: cat.color, fontWeight: 700 }}>{cat.students.length}</span>
                </div>
                {isOpen && (
                  cat.students.length === 0 ? (
                    <div style={{ fontSize: 13, color: SLATE }}>No students in this band.</div>
                  ) : (
                    <table className="cip-table">
                      <thead>
                        <tr>
                          <th>Member Id</th><th>Name</th><th>Section</th><th>Avg.</th>
                          {cat.key === "atRisk" && <th>Courses not started</th>}
                        </tr>
                      </thead>
                      <tbody>
                        {cat.students.map((s, i) => (
                          <tr key={i}>
                            <td style={{ fontSize: 12, color: SLATE }}>{s.id}</td>
                            <td>{s.name}</td>
                            <td>{s.sectionLabel}</td>
                            <td style={{ color: cat.color, fontWeight: 600 }}>{fmtPct(s.avg)}</td>
                            {cat.key === "atRisk" && (
                              <td style={{ fontSize: 12, color: SLATE }}>{s.notStartedCourses.join(", ") || "—"}</td>
                            )}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )
                )}
              </div>
            );
          })}

          {/* password not set — each group is its own export chunk so the PDF
              export doesn't have to rasterize potentially hundreds of student
              rows in a single pass */}
          {insights.totalPasswordIssues > 0 && (
            <>
              <div data-pdf-block="true" className="cip-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 8, marginTop: 16 }}>
                <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY }}>
                  Passwords Not Set
                </div>
              </div>
              {Object.entries(insights.pwBySection).map(([label, g]) => (
                <div
                  key={label}
                  data-pdf-block="true"
                  className="cip-card"
                  style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "14px 22px", marginBottom: 10 }}
                >
                  <div
                    onClick={() => toggleSection(label)}
                    style={{ display: "flex", alignItems: "center", gap: 6, cursor: "pointer", fontWeight: 600, color: NAVY, fontSize: 13.5, marginBottom: 6 }}
                    className="no-print"
                  >
                    {expandedSections[label] ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                    {label} — {g.entries.length} student{g.entries.length !== 1 ? "s" : ""}
                  </div>
                  {expandedSections[label] === false ? null : (
                    <table className="cip-table">
                      <thead><tr><th>Name</th><th>Email</th><th>Account Created</th></tr></thead>
                      <tbody>
                        {g.entries.map((e, i) => (
                          <tr key={i}><td>{e.name}</td><td>{e.email}</td><td>{e.createdTime}</td></tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
              ))}
            </>
          )}

          {/* footer */}
          <div data-pdf-block="true" style={{ textAlign: "center", color: SLATE, fontSize: 11.5, padding: "18px 0 40px", borderTop: `1px solid ${PAPER_LINE}`, marginTop: 10 }}>
            Compiled from CodeTantra group-wise course and password-status exports · Report generated {generatedDate}
          </div>
        </div>
      )}
    </div>
  );
}