import { useState, useMemo, useRef, useCallback } from "react";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import {
  UploadCloud, FileSpreadsheet, X, Download, AlertTriangle, KeyRound,
  Users, GraduationCap, TrendingUp, ChevronDown, ChevronRight,
} from "lucide-react";

// ---------- constants ----------
const NAVY = "#1B2A4A";
const NAVY_SOFT = "#2E4269";
const NAVY_DEEP = "#0F1930";
const MIST = "#8C99BC";
const GOLD = "#B8860F";
const GOLD_SOFT = "#D9A93A";
const PAPER = "#FAF7F0";
const PAPER_LINE = "#E7E0D0";
const INK = "#26241C";
const SLATE = "#6B6656";
const GREEN = "#3D6B4F";
const RUST = "#A8452F";

const COMPLETE_THRESHOLD = 99.5;

// ---------- helpers ----------
// A course cell can mean three different things, and conflating them skews
// every average: a real percentage (progress), explicit "0.00 (Not Started)"
// text or a bare 0 (enrolled, hasn't begun), or "--" / blank-ish placeholder
// text (this course isn't even enabled for this student/section). Only the
// first two should count toward completion math; "--" must be excluded
// entirely rather than silently treated as 0%.
function parseCell(raw) {
  if (raw === null || raw === undefined || raw === "") {
    // A genuinely blank cell is treated as "enrolled, hasn't started" — distinct
    // from an explicit "--" placeholder, which means the course doesn't apply.
    return { value: 0, notStarted: true, enabled: true };
  }
  if (typeof raw === "number") return { value: raw, notStarted: raw <= 0, enabled: true };
  const str = String(raw).trim();
  // "--", "-", "—", "N/A", "NA" and similar dash/placeholder tokens with no digits
  // mean the course isn't enabled for this student/section — exclude entirely.
  if (!/\d/.test(str)) {
    return { value: null, notStarted: false, enabled: false };
  }
  const match = str.match(/-?\d+(\.\d+)?/);
  const num = match ? parseFloat(match[0]) : 0;
  const notStarted = /not started/i.test(str) || num <= 0;
  return { value: num, notStarted, enabled: true };
}

// Section identity always comes from the actual "Groups" column value on the
// row itself (groupStr) — this is what lets a single combined workbook with
// many sections mixed into one sheet split apart correctly, and what lets
// individual per-section files still work the same way. The filename is only
// ever a fallback for the rare row with a blank Groups cell.
function parseSectionMeta(groupStr, fileName) {
  const source = (groupStr && String(groupStr).trim()) || fileName;
  // Section can be a single token ("A", "1") or a multi-part, hyphenated one
  // ("WINDOWS-2") — the third capture group allows internal hyphens so a
  // group like "2024-2028-CSE-WINDOWS-2" keeps its full section identifier
  // ("WINDOWS-2") instead of being truncated to just "WINDOWS".
  const m = String(source).match(/(\d{4}-\d{4})-([A-Za-z]+)-([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)/);
  if (m) {
    return {
      batch: m[1],
      branch: m[2].toUpperCase(),
      section: m[3].toUpperCase(),
      label: `${m[2].toUpperCase()}-${m[3].toUpperCase()}`,
    };
  }
  // No "batch-branch-section" pattern found — trust the raw Groups value
  // itself as the section identity rather than collapsing everything down
  // to the filename, which is what a combined multi-section sheet needs.
  return { batch: "—", branch: "General", section: source, label: source };
}

function shortCourseLabel(header) {
  let h = String(header).replace(/\s*\(%\)\s*$/i, "").trim();
  const parts = h.split(" - ");
  return parts[0].trim();
}

function courseCode(header) {
  let h = String(header).replace(/\s*\(%\)\s*$/i, "").trim();
  const parts = h.split(" - ");
  return parts.length > 1 ? parts[1].trim() : "";
}

function isFooterRow(row) {
  return row.some((c) => typeof c === "string" && /generated by/i.test(c));
}

// Shared by both parsers below: reads the first sheet into a plain header row
// plus filtered body rows (footer/blank rows stripped out).
async function readWorkbookRows(file) {
  const buf = await file.arrayBuffer();
  const wb = XLSX.read(buf, { type: "array" });
  const ws = wb.Sheets[wb.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json(ws, { header: 1, defval: null, blankrows: false });
  if (!rows.length) throw new Error("Empty sheet");
  const header = rows[0].map((h) => (h === null ? "" : String(h).trim()));
  const body = rows.slice(1).filter((r) => r && r.length && !isFooterRow(r) && r[0] !== null && r[1] !== null);
  return { header, body };
}

function findColIdx(header, patterns) {
  for (const p of patterns) {
    const idx = header.findIndex((h) => p.test(String(h).trim()));
    if (idx !== -1) return idx;
  }
  return -1;
}

// Lenient password-not-set parser, used by the dedicated password dropzone.
// Unlike the combined uploader (which only recognizes a password report when
// the header literally contains "Created Time"), this matches Name / Email /
// Groups / a created-date-ish column by pattern, in any order, so an export
// with slightly different column names or ordering still renders correctly
// once the person tells us — by using this dropzone — that it IS a
// password-not-set file.
function parsePasswordSheetLenient(header, body, fileName) {
  const nameIdx = findColIdx(header, [/^name$/i]);
  const emailIdx = findColIdx(header, [/^e-?mail$/i]);
  const groupIdx = findColIdx(header, [/^group/i]);
  const timeIdx = findColIdx(header, [/created/i, /registered/i, /signed?\s*up/i, /date/i, /time/i]);
  if (nameIdx === -1 && emailIdx === -1) {
    throw new Error('Could not find a "Name" or "Email" column — is this a password-not-set export?');
  }
  const entries = body.map((r) => ({
    name: nameIdx >= 0 ? r[nameIdx] ?? "" : "",
    email: emailIdx >= 0 ? r[emailIdx] ?? "" : "",
    groups: groupIdx >= 0 ? r[groupIdx] ?? "" : "",
    createdTime: timeIdx >= 0 ? r[timeIdx] ?? "" : "",
  }));
  const meta = parseSectionMeta(entries[0]?.groups, fileName);
  return { kind: "password", fileName, meta, entries };
}

async function parsePasswordWorkbook(file) {
  const { header, body } = await readWorkbookRows(file);
  return parsePasswordSheetLenient(header, body, file.name);
}

async function parseWorkbook(file) {
  const { header, body } = await readWorkbookRows(file);

  if (header.includes("Created Time")) {
    // password-not-set report: Name, Email, Groups, Created Time
    const nameIdx = header.indexOf("Name");
    const emailIdx = header.indexOf("Email");
    const groupIdx = header.indexOf("Groups");
    const timeIdx = header.indexOf("Created Time");
    const entries = body.map((r) => ({
      name: r[nameIdx] ?? "",
      email: r[emailIdx] ?? "",
      groups: r[groupIdx] ?? "",
      createdTime: timeIdx >= 0 ? r[timeIdx] ?? "" : "",
    }));
    // File-level meta is only an approximation (first row's Groups value) used
    // for the upload-list chip label. Real section grouping happens later,
    // per entry, off each entry's own `groups` value.
    const meta = parseSectionMeta(entries[0]?.groups, file.name);
    return { kind: "password", fileName: file.name, meta, entries };
  }

  if (header.includes("Member Id") || header.includes("Groups")) {
    // group-wise course progress report
    const idIdx = header.indexOf("Member Id");
    const nameIdx = header.indexOf("Name");
    const emailIdx = header.indexOf("Email");
    const groupIdx = header.indexOf("Groups");
    const courseIdxs = header
      .map((h, i) => ({ h, i }))
      .filter(({ h, i }) => i > groupIdx && h && h !== "");
    const courses = courseIdxs.map(({ h }) => ({
      key: h,
      label: shortCourseLabel(h),
      code: courseCode(h),
    }));

    const students = body.map((r) => {
      const courseValues = {};
      let sum = 0;
      let enabledCount = 0;
      courseIdxs.forEach(({ h, i }) => {
        const { value, notStarted, enabled } = parseCell(r[i]);
        courseValues[h] = { value, notStarted, enabled };
        if (enabled) { sum += value; enabledCount++; }
      });
      // avg is null (not 0) when every course is "--" for this student — they
      // simply have no applicable course in this file, which is different
      // from having 0% progress on courses that do apply to them.
      const avg = enabledCount ? sum / enabledCount : null;
      return {
        id: idIdx >= 0 ? r[idIdx] : "",
        name: nameIdx >= 0 ? r[nameIdx] : "",
        email: emailIdx >= 0 ? r[emailIdx] : "",
        groups: groupIdx >= 0 ? r[groupIdx] : "",
        courseValues,
        avg,
      };
    });

    // Same story as above: file-level meta is only a display approximation.
    const meta = parseSectionMeta(students[0]?.groups, file.name);
    return { kind: "course", fileName: file.name, meta, courses, students };
  }

  throw new Error("Unrecognized report format — expected a 'group-wise course' or 'password-not-set' export.");
}

function fmtPct(n) {
  return `${n.toFixed(1)}%`;
}

// ---------- small UI atoms ----------
function StatCard({ icon: Icon, label, value, sub, accent }) {
  return (
    <div style={{
      background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4,
      padding: "18px 20px", flex: "1 1 160px", minWidth: 160,
      borderTop: `3px solid ${accent || GOLD}`,
    }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, color: SLATE, fontSize: 12, letterSpacing: 0.3 }}>
        <Icon size={14} />
        <span>{label}</span>
      </div>
      <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 30, color: NAVY, marginTop: 6, fontWeight: 600 }}>
        {value}
      </div>
      {sub && <div style={{ fontSize: 12, color: SLATE, marginTop: 2 }}>{sub}</div>}
    </div>
  );
}

function barColor(v) {
  if (v >= 70) return GREEN;
  if (v >= 40) return GOLD_SOFT;
  return RUST;
}

// A single L-shaped corner mark. Four of these around a container read as a
// document-intake tray / scan target rather than a generic dashed dropzone —
// the one deliberate flourish on the upload screen.
function CornerBracket({ position, color }) {
  const size = 16;
  const thickness = 2;
  const base = { position: "absolute", width: size, height: size, transition: "border-color 0.15s" };
  const sides = {
    tl: { top: -1, left: -1, borderTop: `${thickness}px solid ${color}`, borderLeft: `${thickness}px solid ${color}` },
    tr: { top: -1, right: -1, borderTop: `${thickness}px solid ${color}`, borderRight: `${thickness}px solid ${color}` },
    bl: { bottom: -1, left: -1, borderBottom: `${thickness}px solid ${color}`, borderLeft: `${thickness}px solid ${color}` },
    br: { bottom: -1, right: -1, borderBottom: `${thickness}px solid ${color}`, borderRight: `${thickness}px solid ${color}` },
  };
  return <div style={{ ...base, ...sides[position] }} />;
}

// Plain HTML/CSS horizontal bar rows — used instead of an SVG chart library so long
// course names wrap naturally onto multiple lines (no fixed-height axis to overlap)
// and the block grows to whatever height the content actually needs, on screen and in print.
// flagThreshold is optional and course-level, distinct from barColor's fixed
// red/gold/green bands: it's a single user-configurable cutoff (courseRiskThreshold)
// used to badge individual course bars as "At Risk" so a SPOC can spot a weak
// course at a glance, separate from any per-student at-risk calculation.
function BarRows({ rows, labelWidth = 200, flagThreshold }) {
  const hasFlagging = typeof flagThreshold === "number";
  const badgeColWidth = 78;
  return (
    <div>
      <div style={{ display: "flex", gap: 10, marginBottom: 8, paddingLeft: labelWidth + 10 }}>
        <div style={{ flex: 1, position: "relative", height: 14 }}>
          {[0, 25, 50, 75, 100].map((v) => (
            <span
              key={v}
              style={{
                position: "absolute", left: `${v}%`, fontSize: 10.5, color: SLATE,
                transform: v === 0 ? "none" : v === 100 ? "translateX(-100%)" : "translateX(-50%)",
              }}
            >
              {v}%
            </span>
          ))}
        </div>
        <div style={{ width: 52, flexShrink: 0 }} />
        {hasFlagging && <div style={{ width: badgeColWidth, flexShrink: 0 }} />}
      </div>
      {rows.map((r, i) => {
        const flagged = hasFlagging && r.value < flagThreshold;
        return (
          <div key={i} style={{ display: "flex", alignItems: "center", gap: 10, margin: "10px 0" }}>
            <div style={{
              width: labelWidth, flexShrink: 0, fontSize: 12.5, color: INK, textAlign: "right",
              paddingRight: 4, lineHeight: 1.35, wordBreak: "break-word",
            }}>
              {r.label}
            </div>
            <div style={{
              flex: 1, background: "#F1ECE0", borderRadius: 3, height: 18, position: "relative",
              overflow: "hidden",
              backgroundImage: "linear-gradient(to right, transparent 24.6%, #E0DACB 24.6%, #E0DACB 25.2%, transparent 25.2%, transparent 49.6%, #E0DACB 49.6%, #E0DACB 50.2%, transparent 50.2%, transparent 74.6%, #E0DACB 74.6%, #E0DACB 75.2%, transparent 75.2%)",
              outline: flagged ? `1.5px solid ${RUST}` : "none",
              outlineOffset: 1,
            }}>
              <div style={{ height: "100%", borderRadius: 3, width: `${Math.max(1.5, Math.min(100, r.value))}%`, background: r.color }} />
            </div>
            <div style={{ width: 52, flexShrink: 0, fontSize: 12.5, color: INK, fontWeight: 600 }}>
              {fmtPct(r.value)}
            </div>
            {hasFlagging && (
              <div style={{ width: badgeColWidth, flexShrink: 0 }}>
                {flagged && (
                  <span style={{
                    display: "inline-flex", alignItems: "center", gap: 3,
                    background: "rgba(168,69,47,0.1)", border: `1px solid ${RUST}`, color: RUST,
                    fontSize: 10.5, fontWeight: 600, padding: "2px 7px", borderRadius: 20,
                    whiteSpace: "nowrap",
                  }}>
                    <AlertTriangle size={10} /> At Risk
                  </span>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

export default function CourseInsightsApp() {
  const [courseFiles, setCourseFiles] = useState([]);
  const [passwordFiles, setPasswordFiles] = useState([]);
  const [busy, setBusy] = useState(false);
  const [generatingPdf, setGeneratingPdf] = useState(false);
  const [pdfError, setPdfError] = useState("");
  const [pdfProgress, setPdfProgress] = useState({ done: 0, total: 0 });
  const [fileErrors, setFileErrors] = useState([]);
  const [threshold, setThreshold] = useState(40); // At Risk / Average boundary
  const [avgMax, setAvgMax] = useState(70); // Average / Good boundary
  const [goodMax, setGoodMax] = useState(90); // Good / Excellent boundary
  const [courseRiskThreshold, setCourseRiskThreshold] = useState(50); // course-level (not student-level) at-risk flag
  const [collegeName, setCollegeName] = useState("");
  const [collegeLogo, setCollegeLogo] = useState(""); // data URL, embeds directly so the exported HTML has no external file dependency
  const [dragOver, setDragOver] = useState(false);
  const [passwordDragOver, setPasswordDragOver] = useState(false);
  const [expandedSections, setExpandedSections] = useState({});
  const inputRef = useRef(null);
  const passwordInputRef = useRef(null);
  const logoInputRef = useRef(null);
  const reportRef = useRef(null);

  const handleLogoFile = useCallback((file) => {
    if (!file) return;
    if (!/^image\//.test(file.type)) return;
    const reader = new FileReader();
    reader.onload = () => setCollegeLogo(reader.result);
    reader.readAsDataURL(file);
  }, []);

  const handleFiles = useCallback(async (fileList) => {
    setBusy(true);
    const newErrors = [];
    const newCourse = [];
    const newPassword = [];
    for (const file of Array.from(fileList)) {
      if (!/\.xlsx?$/i.test(file.name)) {
        newErrors.push(`${file.name}: not an Excel file, skipped.`);
        continue;
      }
      try {
        const parsed = await parseWorkbook(file);
        if (parsed.kind === "course") newCourse.push(parsed);
        else newPassword.push(parsed);
      } catch (e) {
        newErrors.push(`${file.name}: ${e.message || "could not be read"}`);
      }
    }
    setCourseFiles((prev) => {
      const map = new Map(prev.map((f) => [f.fileName, f]));
      newCourse.forEach((f) => map.set(f.fileName, f));
      return Array.from(map.values());
    });
    setPasswordFiles((prev) => {
      const map = new Map(prev.map((f) => [f.fileName, f]));
      newPassword.forEach((f) => map.set(f.fileName, f));
      return Array.from(map.values());
    });
    setFileErrors(newErrors);
    setBusy(false);
  }, []);

  const onDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    if (e.dataTransfer.files?.length) handleFiles(e.dataTransfer.files);
  };

  // Dedicated path for password-not-set files: dropped here, they always go
  // through the lenient parser above rather than the combined auto-detector,
  // so a file whose header doesn't exactly match "Created Time" (different
  // wording, extra columns, reordered columns) still parses correctly instead
  // of silently falling through to the course-report branch and rendering
  // as garbled/empty data.
  const handlePasswordFiles = useCallback(async (fileList) => {
    setBusy(true);
    const newErrors = [];
    const newPassword = [];
    for (const file of Array.from(fileList)) {
      if (!/\.xlsx?$/i.test(file.name)) {
        newErrors.push(`${file.name}: not an Excel file, skipped.`);
        continue;
      }
      try {
        const parsed = await parsePasswordWorkbook(file);
        newPassword.push(parsed);
      } catch (e) {
        newErrors.push(`${file.name}: ${e.message || "could not be read"}`);
      }
    }
    setPasswordFiles((prev) => {
      const map = new Map(prev.map((f) => [f.fileName, f]));
      newPassword.forEach((f) => map.set(f.fileName, f));
      return Array.from(map.values());
    });
    setFileErrors(newErrors);
    setBusy(false);
  }, []);

  const onPasswordDrop = (e) => {
    e.preventDefault();
    setPasswordDragOver(false);
    if (e.dataTransfer.files?.length) handlePasswordFiles(e.dataTransfer.files);
  };

  const removeCourseFile = (name) => setCourseFiles((p) => p.filter((f) => f.fileName !== name));
  const removePasswordFile = (name) => setPasswordFiles((p) => p.filter((f) => f.fileName !== name));
  const clearAll = () => { setCourseFiles([]); setPasswordFiles([]); setFileErrors([]); };

  // ---------- aggregation ----------
  const insights = useMemo(() => {
    if (!courseFiles.length) return null;

    // Group every student by their own "Groups" cell value — not by which
    // file they came from. This is what makes a single combined workbook
    // (many sections stacked in one sheet) split apart into the right
    // sections, while multiple individual per-section files that happen to
    // share a Groups value still merge together correctly.
    const sectionMap = new Map();
    courseFiles.forEach((f) => {
      f.students.forEach((st) => {
        const rawGroup = (st.groups && String(st.groups).trim()) || "";
        const meta = parseSectionMeta(rawGroup, f.fileName);
        const key = meta.label;
        if (!sectionMap.has(key)) {
          sectionMap.set(key, { ...meta, fileNames: new Set(), courseMap: new Map(), students: [] });
        }
        const entry = sectionMap.get(key);
        entry.fileNames.add(f.fileName);
        f.courses.forEach((c) => { if (!entry.courseMap.has(c.key)) entry.courseMap.set(c.key, c); });
        entry.students.push(st);
      });
    });

    const sections = Array.from(sectionMap.values())
      .map((sec) => {
        const courses = Array.from(sec.courseMap.values());
        const studentCount = sec.students.length;
        // Students with avg === null have no course in this file enabled for
        // them at all ("--" everywhere) — exclude them from the average so
        // they don't quietly drag the section's completion rate toward 0.
        const evaluableStudents = sec.students.filter((s) => s.avg !== null);
        const avgOfAvgs = evaluableStudents.length
          ? evaluableStudents.reduce((s, st) => s + st.avg, 0) / evaluableStudents.length
          : 0;
        const perCourse = courses
          .map((c) => {
            let sum = 0, notStartedCount = 0, completeCount = 0, seen = 0;
            sec.students.forEach((st) => {
              const cv = st.courseValues[c.key];
              if (!cv || !cv.enabled) return; // course wasn't provided, or is explicitly "--" (not enabled) for this student
              seen++;
              sum += cv.value;
              if (cv.notStarted) notStartedCount++;
              if (cv.value >= COMPLETE_THRESHOLD) completeCount++;
            });
            return {
              ...c,
              avg: seen ? sum / seen : 0,
              notStartedCount,
              completeCount,
              notStartedRate: seen ? notStartedCount / seen : 0,
              enabledCount: seen,
            };
          })
          // A course nobody in this section has enabled (every student showed
          // "--" for it) isn't part of this section's curriculum at all —
          // drop it here so it doesn't show up as a misleading 0.0% bar. This
          // is evaluated per section (not globally, and not against any fixed
          // expected course count), so a section where only 2 of the file's
          // courses are enabled, and another where all 3 are, are each
          // reported against just the courses that actually apply to them.
          .filter((c) => c.enabledCount > 0);
        const atRisk = evaluableStudents.filter((s) => s.avg < threshold);
        const startedCount = sec.students.filter((s) => Object.values(s.courseValues).some((cv) => cv.enabled && !cv.notStarted)).length;
        const notApplicableCount = sec.students.filter((s) => s.avg === null).length;
        const notStartedCount = studentCount - startedCount - notApplicableCount;
        return {
          batch: sec.batch, branch: sec.branch, section: sec.section, label: sec.label,
          fileName: Array.from(sec.fileNames).join(", "),
          studentCount, evaluableCount: evaluableStudents.length, avgOfAvgs, perCourse, atRisk, startedCount, notStartedCount, notApplicableCount,
          students: sec.students, courses,
        };
      })
      .sort((a, b) => a.label.localeCompare(b.label));

    const totalStudents = sections.reduce((s, sec) => s + sec.studentCount, 0);
    const totalEvaluable = sections.reduce((s, sec) => s + sec.evaluableCount, 0);
    // Weighted by evaluable students (those with at least one enabled course),
    // not total headcount, so sections full of "--" placeholders don't drag
    // the overall figure down with averages that were never really 0%.
    const overallAvg = totalEvaluable
      ? sections.reduce((s, sec) => s + sec.avgOfAvgs * sec.evaluableCount, 0) / totalEvaluable
      : 0;
    const totalAtRisk = sections.reduce((s, sec) => s + sec.atRisk.length, 0);
    const totalNotApplicable = sections.reduce((s, sec) => s + sec.notApplicableCount, 0);

    // password issues joined to sections — grouped the same way, by each
    // entry's own Groups value, so a combined password export splits apart
    // just like the combined course export does.
    const pwBySection = {};
    passwordFiles.forEach((f) => {
      f.entries.forEach((entry) => {
        const rawGroup = (entry.groups && String(entry.groups).trim()) || "";
        const meta = parseSectionMeta(rawGroup, f.fileName);
        const key = meta.label;
        if (!pwBySection[key]) pwBySection[key] = { meta, entries: [] };
        pwBySection[key].entries.push(entry);
      });
    });
    const totalPasswordIssues = Object.values(pwBySection).reduce((s, g) => s + g.entries.length, 0);

    // enrollment/activation summary table (mirrors the CodeTantra group dashboard view)
    const enrollment = sections.map((sec) => {
      const passwordNotSet = pwBySection[sec.label]?.entries.length || 0;
      return {
        label: sec.label,
        started: sec.startedCount,
        notStarted: sec.notStartedCount,
        notApplicable: sec.notApplicableCount,
        passwordNotSet,
        subTotal: sec.studentCount + passwordNotSet,
      };
    });
    const enrollmentTotals = enrollment.reduce((acc, r) => ({
      started: acc.started + r.started,
      notStarted: acc.notStarted + r.notStarted,
      notApplicable: acc.notApplicable + r.notApplicable,
      passwordNotSet: acc.passwordNotSet + r.passwordNotSet,
      subTotal: acc.subTotal + r.subTotal,
    }), { started: 0, notStarted: 0, notApplicable: 0, passwordNotSet: 0, subTotal: 0 });

    // branch grouping for course comparison charts
    const branches = {};
    sections.forEach((sec) => {
      if (!branches[sec.branch]) branches[sec.branch] = { sections: [], courseAgg: new Map() };
      branches[sec.branch].sections.push(sec);
      sec.perCourse.forEach((c) => {
        const agg = branches[sec.branch].courseAgg.get(c.key) || {
          label: c.label, code: c.code, sumPct: 0, students: 0, notStarted: 0,
        };
        agg.sumPct += c.avg * sec.studentCount;
        agg.students += sec.studentCount;
        agg.notStarted += c.notStartedCount;
        branches[sec.branch].courseAgg.set(c.key, agg);
      });
    });
    const branchCharts = Object.entries(branches).map(([branch, data]) => ({
      branch,
      courses: Array.from(data.courseAgg.values()).map((c) => ({
        ...c,
        avg: c.students ? c.sumPct / c.students : 0,
        notStartedRate: c.students ? c.notStarted / c.students : 0,
      })),
    }));

    // Every student, flattened across all sections, with section label and
    // not-started course list attached — the base list the performance
    // categories below are filtered from. notStartedCourses only lists
    // courses that are actually enabled for the student; a "--" course
    // isn't something they "haven't started", it just doesn't apply to them.
    const allStudentsFlat = sections.flatMap((sec) => sec.students.map((s) => ({
      ...s,
      sectionLabel: sec.label,
      notStartedCourses: sec.courses
        .filter((c) => s.courseValues[c.key] && s.courseValues[c.key].enabled && s.courseValues[c.key].notStarted)
        .map((c) => c.label),
    })));

    // Full-picture performance bands: everyone with a measurable average is
    // shown, not just the at-risk group, so the report covers at-risk /
    // average / good / excellent completion. Boundaries are user-configurable
    // (threshold, avgMax, goodMax) rather than fixed, since what counts as
    // "good" varies by cohort, course difficulty, and how far into the term
    // it is. Guard against the boundaries being dragged out of order so the
    // bands never invert into an impossible range.
    const b1 = threshold;
    const b2 = Math.max(avgMax, b1);
    const b3 = Math.max(goodMax, b2);
    const categoryDefs = [
      { key: "atRisk", title: "At Risk", range: `below ${b1}%`, color: RUST, test: (avg) => avg < b1 },
      { key: "average", title: "Average", range: `${b1}%–${(b2 - 0.1).toFixed(1)}%`, color: GOLD, test: (avg) => avg >= b1 && avg < b2 },
      { key: "good", title: "Good", range: `${b2}%–${(b3 - 0.1).toFixed(1)}%`, color: NAVY_SOFT, test: (avg) => avg >= b2 && avg < b3 },
      { key: "excellent", title: "Excellent", range: `${b3}% and above`, color: GREEN, test: (avg) => avg >= b3 },
    ];
    // Students with avg === null have zero enabled courses in this dataset
    // ("--" across the board) — they can't be scored into any completion
    // band, so they get their own bucket instead of silently vanishing or
    // dragging "At Risk" down with a fake 0%.
    const evaluableFlat = allStudentsFlat.filter((s) => s.avg !== null);
    const notApplicableFlat = allStudentsFlat.filter((s) => s.avg === null);
    const categorizedStudents = categoryDefs.map((c) => ({
      ...c,
      students: evaluableFlat.filter((s) => c.test(s.avg)).sort((a, b) => b.avg - a.avg),
    }));
    if (notApplicableFlat.length) {
      categorizedStudents.push({
        key: "notApplicable",
        title: "No Enabled Courses",
        range: `no course in this report applies to them`,
        color: SLATE,
        students: notApplicableFlat.sort((a, b) => a.name.localeCompare(b.name)),
      });
    }
    const atRiskAll = categorizedStudents[0].students;

    const topPerformers = [...evaluableFlat].sort((a, b) => b.avg - a.avg).slice(0, 5);

    const sortedByAvg = [...sections].sort((a, b) => a.avgOfAvgs - b.avgOfAvgs);
    const weakestSection = sortedByAvg[0];
    const strongestSection = sortedByAvg[sortedByAvg.length - 1];

    let weakestCourse = null;
    branchCharts.forEach((b) => {
      b.courses.forEach((c) => {
        if (!weakestCourse || c.notStartedRate > weakestCourse.notStartedRate) {
          weakestCourse = { ...c, branch: b.branch };
        }
      });
    });

    const batches = Array.from(new Set(sections.map((s) => s.batch))).filter((b) => b !== "—");

    return {
      sections, totalStudents, totalEvaluable, overallAvg, totalAtRisk, totalNotApplicable, pwBySection, totalPasswordIssues,
      branchCharts, allStudentsFlat, categorizedStudents, atRiskAll, topPerformers,
      weakestSection, strongestSection, weakestCourse, batches, enrollment, enrollmentTotals,
    };
  }, [courseFiles, passwordFiles, threshold, avgMax, goodMax]);

  // Course-level at-risk count: how many (section, course) pairs fall below the
  // configurable course-risk threshold. Kept outside the insights useMemo since it
  // only re-slices sec.perCourse (already computed there) by courseRiskThreshold —
  // recomputing this alone on every threshold tweak is cheap and avoids widening
  // the memo's dependency list.
  const totalAtRiskCourses = insights
    ? insights.sections.reduce((sum, sec) => sum + sec.perCourse.filter((c) => c.avg < courseRiskThreshold).length, 0)
    : 0;

  const generatedDate = new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });

  const toggleSection = (label) => setExpandedSections((p) => ({ ...p, [label]: !p[label] }));

  // Printing/exporting directly from inside this sandboxed preview is unreliable,
  // so instead we package the rendered report into a standalone HTML file the
  // person can open in a normal browser tab, where "Print / Save as PDF" always works.
  const downloadReport = () => {
    if (!reportRef.current) return;
    const contentHTML = reportRef.current.outerHTML;
    const cleanCollege = collegeName.trim();
    const escapedCollege = cleanCollege.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    const docTitle = cleanCollege ? `${escapedCollege} — Course Progress Report` : "Course Progress Report";
    const faviconHref = collegeLogo || "data:image/svg+xml," + encodeURIComponent(
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="18" fill="${NAVY}"/><text x="50" y="66" font-size="58" text-anchor="middle">🎓</text></svg>`
    );
    const doc = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<link rel="icon" href="${faviconHref}" />
<title>${docTitle}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@500;600;700&family=Inter:wght@400;500;600;700&display=swap');
  * { box-sizing: border-box; }
  * { -webkit-print-color-adjust: exact; print-color-adjust: exact; color-adjust: exact; }
  body { font-family: 'Inter', -apple-system, sans-serif; background: ${PAPER}; margin: 0; padding: 28px; color: ${INK}; }
  table.cip-table { width: 100%; border-collapse: collapse; font-size: 13px; }
  table.cip-table th { text-align: left; font-weight: 600; color: ${SLATE}; font-size: 11px;
    letter-spacing: 0.4px; text-transform: uppercase; padding: 8px 10px; border-bottom: 2px solid ${NAVY}; }
  table.cip-table td { padding: 8px 10px; border-bottom: 1px solid ${PAPER_LINE}; }
  table.cip-table tr:last-child td { border-bottom: none; }
  .print-bar { position: sticky; top: 0; display: flex; justify-content: flex-end; padding: 10px 0 18px; background: ${PAPER}; z-index: 10; }
  .print-btn { background: ${GOLD_SOFT}; color: ${NAVY}; font-weight: 600; font-size: 14px; border: none;
    padding: 10px 20px; border-radius: 4px; cursor: pointer; font-family: 'Inter', sans-serif; }
  /* Let cards flow and pack naturally onto pages — only keep a single card from
     splitting across a page boundary. No forced page-before, so the print engine
     fits as many cards as actually fit on each page based on real height. */
  .cip-card, .cip-chart-card { break-inside: avoid; -webkit-column-break-inside: avoid; page-break-inside: avoid; }
  table.cip-table tr { break-inside: avoid; page-break-inside: avoid; }
  @media print {
    .print-bar { display: none; }
    .print-bar-hint { display: none; }
    body { padding: 0; background: #fff; }
    * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; color-adjust: exact !important; }
  }
</style>
</head>
<body>
  <div class="print-bar"><button class="print-btn" onclick="window.print()">Print / Save as PDF</button></div>
  <div style="font-size: 12px; color: ${SLATE}; text-align: right; margin-top: -8px;" class="print-bar-hint">
    Tip: in the print dialog — turn <strong>"Background graphics"</strong> ON (so bars/shading show up) and
    <strong>"Headers and footers"</strong> OFF (so the browser doesn't add its own date/time and file path to each page).
  </div>
  ${contentHTML}
</body>
</html>`;
    const blob = new Blob([doc], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const slug = reportFileSlug();
    a.download = slug ? `${slug}-course-progress-report.html` : "course-progress-report.html";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const reportFileSlug = () => {
    const clean = collegeName.trim();
    return clean ? clean.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") : "";
  };

  // Direct-to-PDF export: snapshots each marked report chunk ([data-pdf-block])
  // as an image via html2canvas, then packs those images onto A4 pages with
  // jsPDF — same "fit as many blocks as fit, only break when a block doesn't
  // fit" logic as the print stylesheet, but producing real PDF bytes so
  // there's no print dialog step. A block taller than a page (a long table)
  // is sliced across pages so nothing gets cut off.
  //
  // Large reports were triggering the browser's "Page Unresponsive" warning
  // because html2canvas does heavy synchronous rasterization work; running
  // many of those back-to-back with no gap blocks the main thread long enough
  // to trip Chrome's watchdog. Two things fix that: (1) yielding to the event
  // loop between every block via a 0ms timeout, which resets the watchdog and
  // lets the UI repaint, and (2) breaking big chunks like the password-not-set
  // list into one block per section instead of one giant block.
  const yieldToBrowser = () => new Promise((resolve) => setTimeout(resolve, 0));

  const downloadPdf = async () => {
    if (!reportRef.current) return;
    setGeneratingPdf(true);
    setPdfError("");
    setPdfProgress({ done: 0, total: 0 });
    await yieldToBrowser(); // let the "Generating PDF…" button state paint before heavy work starts

    try {
      const pageWidthMm = 210; // A4
      const pageHeightMm = 297;
      const marginMm = 10;
      const usableWidthMm = pageWidthMm - marginMm * 2;
      const usableHeightMm = pageHeightMm - marginMm * 2;
      const gapMm = 4;

      const pdf = new jsPDF({ unit: "mm", format: "a4", compress: true });
      let cursorY = marginMm;
      let firstBlock = true;

      const blocks = Array.from(reportRef.current.querySelectorAll('[data-pdf-block="true"]')).filter(
        (el) => el.offsetHeight > 0
      );
      setPdfProgress({ done: 0, total: blocks.length });

      for (let i = 0; i < blocks.length; i++) {
        const el = blocks[i];
        const canvas = await html2canvas(el, {
          scale: 1.5,
          backgroundColor: "#ffffff",
          useCORS: true,
          logging: false,
        });

        const pxPerMm = canvas.width / usableWidthMm;
        const usableHeightPx = usableHeightMm * pxPerMm;
        const totalHeightPx = canvas.height;
        let renderedPx = 0;

        while (renderedPx < totalHeightPx) {
          const sliceHeightPx = Math.min(usableHeightPx, totalHeightPx - renderedPx);
          const sliceHeightMm = sliceHeightPx / pxPerMm;

          // move to a fresh page if this slice won't fit in the remaining space
          if (!firstBlock && cursorY + sliceHeightMm > pageHeightMm - marginMm && cursorY > marginMm) {
            pdf.addPage();
            cursorY = marginMm;
          }
          if (renderedPx > 0 && cursorY !== marginMm) {
            // a slice that's a continuation of an oversized block always starts a fresh page
            pdf.addPage();
            cursorY = marginMm;
          }

          const sliceCanvas = document.createElement("canvas");
          sliceCanvas.width = canvas.width;
          sliceCanvas.height = sliceHeightPx;
          sliceCanvas.getContext("2d").drawImage(
            canvas, 0, renderedPx, canvas.width, sliceHeightPx, 0, 0, canvas.width, sliceHeightPx
          );
          const sliceData = sliceCanvas.toDataURL("image/png");
          pdf.addImage(sliceData, "PNG", marginMm, cursorY, usableWidthMm, sliceHeightMm);

          cursorY += sliceHeightMm;
          renderedPx += sliceHeightPx;
          firstBlock = false;
        }
        cursorY += gapMm;

        setPdfProgress({ done: i + 1, total: blocks.length });
        await yieldToBrowser(); // give the browser a chance to paint/respond before the next heavy capture
      }

      const slug = reportFileSlug();
      pdf.save(slug ? `${slug}-course-progress-report.pdf` : "course-progress-report.pdf");
    } catch (err) {
      console.error(err);
      setPdfError("Couldn't generate the PDF in this browser. Try the HTML download and print it instead.");
    } finally {
      setGeneratingPdf(false);
    }
  };

  return (
    <div style={{
      fontFamily: "'Inter', -apple-system, sans-serif", background: PAPER, minHeight: "100vh",
      color: INK, paddingBottom: 60,
    }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@500;600;700&family=Inter:wght@400;500;600;700&display=swap');
        * { box-sizing: border-box; }
        .cip-btn { cursor: pointer; border: none; font-family: inherit; }
        .cip-btn:disabled { opacity: 0.5; cursor: not-allowed; }
        table.cip-table { width: 100%; border-collapse: collapse; font-size: 13px; }
        table.cip-table th { text-align: left; font-weight: 600; color: ${SLATE}; font-size: 11px;
          letter-spacing: 0.4px; text-transform: uppercase; padding: 8px 10px; border-bottom: 2px solid ${NAVY}; }
        table.cip-table td { padding: 8px 10px; border-bottom: 1px solid ${PAPER_LINE}; }
        table.cip-table tr:last-child td { border-bottom: none; }
        @media print {
          .no-print { display: none !important; }
          body, .cip-root { background: #fff !important; }
          .cip-page { box-shadow: none !important; margin: 0 !important; padding: 0 !important; max-width: none !important; }
          .cip-card, .cip-chart-card { break-inside: avoid; page-break-inside: avoid; }
          table.cip-table tr { break-inside: avoid; page-break-inside: avoid; }
          * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; color-adjust: exact !important; }
        }
      `}</style>

      {/* ---------- Upload / control zone (no-print) ---------- */}
      <div className="no-print" style={{ background: `linear-gradient(180deg, ${NAVY} 0%, ${NAVY_DEEP} 100%)` }}>
        <div style={{ height: 3, background: `linear-gradient(90deg, transparent, ${GOLD_SOFT}, transparent)` }} />
        <div style={{ padding: "34px 32px 26px" }}>
          <div style={{ maxWidth: 1080, margin: "0 auto" }}>

            {/* masthead: seal + wordmark beside the document-intake tray */}
            <div style={{ display: "flex", gap: 36, flexWrap: "wrap", marginBottom: 24 }}>
              <div style={{ flex: "1 1 360px", minWidth: 280 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 14 }}>
                  <div style={{
                    width: 46, height: 46, borderRadius: "50%", border: `1.5px solid ${GOLD_SOFT}`,
                    display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0,
                    background: "rgba(217,169,58,0.06)",
                  }}>
                    <GraduationCap size={20} color={GOLD_SOFT} />
                  </div>
                  <div>
                    <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 25, fontWeight: 700, color: "#fff", lineHeight: 1.15 }}>
                      Course Progress Insights
                    </div>
                    <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontStyle: "italic", fontSize: 13.5, color: GOLD_SOFT, marginTop: 3 }}>
                      Compiled for your SPOC, section by section
                    </div>
                  </div>
                </div>
                <div style={{ color: MIST, fontSize: 13, lineHeight: 1.75, maxWidth: 440 }}>
                  Upload section-wise CodeTantra course reports — individual per-section files, or one combined
                  workbook with every section stacked together. Sections are always read from each row's
                  "Groups" column, and everything compiles into a single consolidated report.
                </div>
              </div>

              <div style={{ flex: "1 1 320px", minWidth: 280 }}>
                <div
                  onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
                  onDragLeave={() => setDragOver(false)}
                  onDrop={onDrop}
                  onClick={() => inputRef.current?.click()}
                  style={{
                    position: "relative", border: `1px solid ${dragOver ? GOLD_SOFT : "rgba(217,169,58,0.22)"}`,
                    borderRadius: 3, padding: "28px 22px", textAlign: "center", cursor: "pointer",
                    background: dragOver ? "rgba(217,169,58,0.08)" : "rgba(255,255,255,0.02)",
                    transition: "all 0.15s", height: "100%", boxSizing: "border-box",
                  }}
                >
                  <CornerBracket position="tl" color={dragOver ? GOLD_SOFT : "rgba(217,169,58,0.4)"} />
                  <CornerBracket position="tr" color={dragOver ? GOLD_SOFT : "rgba(217,169,58,0.4)"} />
                  <CornerBracket position="bl" color={dragOver ? GOLD_SOFT : "rgba(217,169,58,0.4)"} />
                  <CornerBracket position="br" color={dragOver ? GOLD_SOFT : "rgba(217,169,58,0.4)"} />
                  <UploadCloud size={24} color={GOLD_SOFT} style={{ marginBottom: 8 }} />
                  <div style={{ color: "#fff", fontSize: 14, fontWeight: 500 }}>
                    {busy ? "Reading files…" : "Drop .xlsx files here, or click to browse"}
                  </div>
                  <div style={{ color: MIST, fontSize: 12, marginTop: 4, lineHeight: 1.6 }}>
                    Group-wise course reports and password-not-set reports — individual sections or one
                    combined sheet, any number at once
                  </div>
                  <input
                    ref={inputRef} type="file" multiple accept=".xlsx,.xls"
                    style={{ display: "none" }}
                    onChange={(e) => e.target.files?.length && handleFiles(e.target.files)}
                  />
                </div>

                {/* Dedicated password-not-set dropzone. Separate from the box above
                    so a password export that isn't being detected/rendered correctly
                    through the combined uploader can be dropped here instead — this
                    path always parses it as a password report using flexible column
                    matching, rather than relying on an exact "Created Time" header. */}
                <div
                  onDragOver={(e) => { e.preventDefault(); setPasswordDragOver(true); }}
                  onDragLeave={() => setPasswordDragOver(false)}
                  onDrop={onPasswordDrop}
                  onClick={() => passwordInputRef.current?.click()}
                  style={{
                    marginTop: 10, border: `1px dashed ${passwordDragOver ? GOLD_SOFT : "rgba(217,169,58,0.3)"}`,
                    borderRadius: 3, padding: "12px 14px", cursor: "pointer",
                    background: passwordDragOver ? "rgba(217,169,58,0.08)" : "rgba(255,255,255,0.02)",
                    display: "flex", alignItems: "center", gap: 10, transition: "all 0.15s",
                  }}
                >
                  <KeyRound size={15} color={GOLD_SOFT} style={{ flexShrink: 0 }} />
                  <div style={{ minWidth: 0 }}>
                    <div style={{ color: "#fff", fontSize: 12.5, fontWeight: 500 }}>
                      {busy ? "Reading…" : "Password-not-set file not rendering right? Drop it here separately"}
                    </div>
                    <div style={{ color: MIST, fontSize: 11, marginTop: 2 }}>
                      Parsed as a password report regardless of exact column names/order
                    </div>
                  </div>
                  <input
                    ref={passwordInputRef} type="file" multiple accept=".xlsx,.xls"
                    style={{ display: "none" }}
                    onChange={(e) => e.target.files?.length && handlePasswordFiles(e.target.files)}
                  />
                </div>
              </div>
            </div>

            {/* letterhead fields — college name & logo, set off from the masthead by a hairline */}
            <div style={{
              borderTop: "1px solid rgba(255,255,255,0.09)", paddingTop: 18,
              display: "flex", gap: 20, flexWrap: "wrap",
            }}>
              <label style={{ display: "block", flex: "1 1 320px" }}>
                <div style={{ color: MIST, fontSize: 12.5, marginBottom: 5 }}>College / Institute name (shown on the report)</div>
                <input
                  type="text"
                  value={collegeName}
                  onChange={(e) => setCollegeName(e.target.value)}
                  placeholder="e.g. Sreenidhi Institute of Science and Technology"
                  style={{
                    width: "100%", maxWidth: 420, padding: "8px 10px", borderRadius: 4,
                    border: "1px solid #3E5079", background: "#152038", color: "#fff", fontSize: 13.5,
                  }}
                />
              </label>

              <div style={{ flex: "0 0 auto" }}>
                <div style={{ color: MIST, fontSize: 12.5, marginBottom: 5 }}>College logo (optional)</div>
                <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  {collegeLogo && (
                    <img
                      src={collegeLogo} alt="College logo preview"
                      style={{ height: 34, maxWidth: 90, objectFit: "contain", background: "#fff", borderRadius: 3, padding: 2 }}
                    />
                  )}
                  <button
                    type="button"
                    className="cip-btn"
                    onClick={() => logoInputRef.current?.click()}
                    style={{
                      background: "rgba(255,255,255,0.06)", color: "#fff", fontSize: 12.5,
                      border: "1px solid #3E5079", borderRadius: 4, padding: "7px 12px",
                    }}
                  >
                    {collegeLogo ? "Change logo" : "Upload logo"}
                  </button>
                  {collegeLogo && (
                    <X
                      size={16}
                      style={{ cursor: "pointer", color: MIST }}
                      onClick={() => setCollegeLogo("")}
                    />
                  )}
                  <input
                    ref={logoInputRef} type="file" accept="image/*"
                    style={{ display: "none" }}
                    onChange={(e) => handleLogoFile(e.target.files?.[0])}
                  />
                </div>
              </div>
            </div>

            {fileErrors.length > 0 && (
              <div style={{ marginTop: 16, background: "rgba(168,69,47,0.15)", border: `1px solid ${RUST}`, borderRadius: 4, padding: "10px 14px" }}>
                {fileErrors.map((e, i) => (
                  <div key={i} style={{ color: "#F3C9BE", fontSize: 12.5, display: "flex", gap: 6, alignItems: "flex-start" }}>
                    <AlertTriangle size={13} style={{ marginTop: 2, flexShrink: 0 }} /> {e}
                  </div>
                ))}
              </div>
            )}

            {(courseFiles.length > 0 || passwordFiles.length > 0) && (
              <div style={{ marginTop: 16, display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" }}>
                {courseFiles.map((f) => {
                  const distinctGroups = new Set(
                    f.students.map((s) => (s.groups && String(s.groups).trim()) || "Unspecified")
                  ).size;
                  return (
                    <span key={f.fileName} style={{
                      display: "inline-flex", alignItems: "center", gap: 6,
                      background: "rgba(255,255,255,0.04)", border: "1px solid rgba(217,169,58,0.28)",
                      color: "#fff", fontSize: 12, padding: "5px 6px 5px 10px", borderRadius: 3,
                    }}>
                      <FileSpreadsheet size={12} color={GOLD_SOFT} />
                      {f.fileName}{" "}
                      <span style={{ color: MIST }}>
                        · {f.students.length} students{distinctGroups > 1 ? ` · ${distinctGroups} sections` : ""}
                      </span>
                      <X size={13} style={{ cursor: "pointer", marginLeft: 2 }} onClick={() => removeCourseFile(f.fileName)} />
                    </span>
                  );
                })}
                {passwordFiles.map((f) => {
                  const distinctGroups = new Set(
                    f.entries.map((e) => (e.groups && String(e.groups).trim()) || "Unspecified")
                  ).size;
                  return (
                    <span key={f.fileName} style={{
                      display: "inline-flex", alignItems: "center", gap: 6,
                      background: "rgba(255,255,255,0.04)", border: "1px solid rgba(217,169,58,0.28)",
                      color: "#fff", fontSize: 12, padding: "5px 6px 5px 10px", borderRadius: 3,
                    }}>
                      <KeyRound size={12} color={GOLD_SOFT} />
                      {f.fileName}{" "}
                      <span style={{ color: MIST }}>
                        · {f.entries.length} no password{distinctGroups > 1 ? ` · ${distinctGroups} sections` : ""}
                      </span>
                      <X size={13} style={{ cursor: "pointer", marginLeft: 2 }} onClick={() => removePasswordFile(f.fileName)} />
                    </span>
                  );
                })}
                <button className="cip-btn" onClick={clearAll} style={{
                  background: "none", color: MIST, fontSize: 12, textDecoration: "underline", padding: "4px 6px",
                }}>
                  clear all
                </button>
              </div>
            )}

            {insights && (
              <div style={{ marginTop: 18, display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}>
                  <label style={{ color: MIST, fontSize: 12.5, display: "flex", alignItems: "center", gap: 8 }}>
                    At-risk threshold (average % below)
                    <input
                      type="number" min={0} max={100} value={threshold}
                      onChange={(e) => setThreshold(Number(e.target.value) || 0)}
                      style={{ width: 56, padding: "4px 6px", borderRadius: 4, border: "1px solid #3E5079", background: "#152038", color: "#fff" }}
                    />
                  </label>
                  <label style={{ color: MIST, fontSize: 12.5, display: "flex", alignItems: "center", gap: 8 }}>
                    Average performance threshold (average % from)
                    <input
                      type="number" min={0} max={100} value={threshold}
                      onChange={(e) => setThreshold(Number(e.target.value) || 0)}
                      style={{ width: 56, padding: "4px 6px", borderRadius: 4, border: "1px solid #3E5079", background: "#152038", color: "#fff" }}
                    />
                  </label>
                  <label style={{ color: MIST, fontSize: 12.5, display: "flex", alignItems: "center", gap: 8 }}>
                    Good performance threshold (average % from)
                    <input
                      type="number" min={0} max={100} value={avgMax}
                      onChange={(e) => setAvgMax(Number(e.target.value) || 0)}
                      style={{ width: 56, padding: "4px 6px", borderRadius: 4, border: "1px solid #3E5079", background: "#152038", color: "#fff" }}
                    />
                  </label>
                  <label style={{ color: MIST, fontSize: 12.5, display: "flex", alignItems: "center", gap: 8 }}>
                    Excellent performance threshold (average % from)
                    <input
                      type="number" min={0} max={100} value={goodMax}
                      onChange={(e) => setGoodMax(Number(e.target.value) || 0)}
                      style={{ width: 56, padding: "4px 6px", borderRadius: 4, border: "1px solid #3E5079", background: "#152038", color: "#fff" }}
                    />
                  </label>
                  <label style={{ color: MIST, fontSize: 12.5, display: "flex", alignItems: "center", gap: 8 }}>
                    Course at-risk threshold (course avg % below)
                    <input
                      type="number" min={0} max={100} value={courseRiskThreshold}
                      onChange={(e) => setCourseRiskThreshold(Number(e.target.value) || 0)}
                      style={{ width: 56, padding: "4px 6px", borderRadius: 4, border: "1px solid #3E5079", background: "#152038", color: "#fff" }}
                    />
                  </label>
                </div>
                <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 10 }}>
                  <button
                    className="cip-btn"
                    onClick={downloadReport}
                    style={{
                      display: "inline-flex", alignItems: "center", gap: 6,
                      background: "none", color: MIST, fontSize: 12.5,
                      padding: "9px 4px", textDecoration: "underline",
                    }}
                  >
                    Download as HTML instead
                  </button>
                  <button
                    className="cip-btn"
                    onClick={downloadPdf}
                    disabled={generatingPdf}
                    style={{
                      display: "inline-flex", alignItems: "center", gap: 8,
                      background: `linear-gradient(180deg, ${GOLD_SOFT}, ${GOLD})`, color: NAVY, fontWeight: 600, fontSize: 13.5,
                      padding: "9px 18px", borderRadius: 4, border: "none",
                    }}
                  >
                    <Download size={15} />
                    {generatingPdf
                      ? pdfProgress.total > 0
                        ? `Generating PDF… (${pdfProgress.done}/${pdfProgress.total})`
                        : "Generating PDF…"
                      : "Download PDF report"}
                  </button>
                </div>
                {pdfError && (
                  <div style={{ width: "100%", color: "#F3C9BE", fontSize: 12.5, display: "flex", gap: 6, alignItems: "flex-start" }}>
                    <AlertTriangle size={13} style={{ marginTop: 2, flexShrink: 0 }} /> {pdfError}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ---------- Report ---------- */}
      {!insights && (
        <div style={{ maxWidth: 560, margin: "56px auto", textAlign: "center" }}>
          <div style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "40px 32px" }}>
            <div style={{
              width: 48, height: 48, borderRadius: "50%", border: `1.5px solid ${GOLD_SOFT}`,
              display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 18px",
            }}>
              <FileSpreadsheet size={20} color={GOLD} />
            </div>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 19, fontWeight: 600, color: NAVY, marginBottom: 8 }}>
              Awaiting your first report
            </div>
            <div style={{ fontSize: 13.5, color: SLATE, lineHeight: 1.75 }}>
              Upload at least one group-wise course report above to build the insights report. Every section
              is read automatically from the "Groups" column on each row — one file per section, or a single
              combined workbook with all sections together.
            </div>
          </div>
        </div>
      )}


      {insights && (
        <div ref={reportRef} className="cip-page" style={{ maxWidth: 1080, margin: "28px auto 0", padding: "0 32px" }}>

          {/* report header */}
          <div data-pdf-block="true" style={{ display: "flex", alignItems: "center", gap: 16, borderBottom: `3px solid ${NAVY}`, paddingBottom: 14, marginBottom: 22 }}>
            {collegeLogo && (
              <img
                src={collegeLogo} alt="College logo"
                style={{ height: 52, maxWidth: 100, objectFit: "contain", flexShrink: 0 }}
              />
            )}
            <div style={{ flex: 1, minWidth: 0 }}>
              {collegeName.trim() && (
                <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 15, fontWeight: 600, color: GOLD, letterSpacing: 0.3, marginBottom: 4, textTransform: "uppercase" }}>
                  {collegeName.trim()}
                </div>
              )}
              <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 26, fontWeight: 700, color: NAVY }}>
                Course Progress Report{insights.batches.length ? ` — ${insights.batches.join(", ")} Batch` : ""}
              </div>
              <div style={{ fontSize: 12.5, color: SLATE, marginTop: 4 }}>
                Generated {generatedDate} · {insights.sections.length} section{insights.sections.length !== 1 ? "s" : ""} ·
                {" "}{insights.totalStudents} students · at-risk cutoff: below {threshold}% average
              </div>
            </div>
          </div>

          {/* summary cards */}
          <div data-pdf-block="true" style={{ display: "flex", gap: 14, flexWrap: "wrap", marginBottom: 26 }} className="cip-card">
            <StatCard
              icon={Users}
              label="Total Students"
              value={insights.totalStudents + insights.totalPasswordIssues}
              sub={insights.totalPasswordIssues > 0 ? `${insights.totalStudents} in course reports + ${insights.totalPasswordIssues} password not set` : undefined}
              accent={NAVY}
            />
            <StatCard icon={GraduationCap} label="Sections Covered" value={insights.sections.length} accent={NAVY} />
            <StatCard icon={TrendingUp} label="Overall Avg. Completion" value={fmtPct(insights.overallAvg)} accent={barColor(insights.overallAvg)} />
            <StatCard icon={AlertTriangle} label={`At Risk (< ${threshold}%)`} value={insights.totalAtRisk} sub={`${((insights.totalAtRisk / insights.totalEvaluable) * 100 || 0).toFixed(1)}% of students`} accent={RUST} />
            <StatCard
              icon={TrendingUp}
              label="Excellent (90%+)"
              value={insights.categorizedStudents.find((c) => c.key === "excellent")?.students.length || 0}
              accent={GREEN}
            />
            <StatCard icon={KeyRound} label="Passwords Not Set" value={insights.totalPasswordIssues} accent={GOLD} />
            <StatCard
              icon={AlertTriangle}
              label="Courses At Risk"
              value={totalAtRiskCourses}
              sub={`below ${courseRiskThreshold}% avg. completion`}
              accent={totalAtRiskCourses > 0 ? RUST : GREEN}
            />
            {insights.totalNotApplicable > 0 && (
              <StatCard
                icon={AlertTriangle}
                label="No Enabled Courses"
                value={insights.totalNotApplicable}
                sub={`shown as "--" in the source file`}
                accent={SLATE}
              />
            )}
          </div>

          {/* key observations */}
          <div data-pdf-block="true" className="cip-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 26 }}>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY, marginBottom: 10 }}>
              Key Observations
            </div>
            <ul style={{ margin: 0, paddingLeft: 18, fontSize: 13.5, lineHeight: 1.85, color: INK }}>
              {insights.strongestSection && insights.weakestSection && insights.sections.length > 1 && (
                <li>
                  <strong>{insights.strongestSection.label}</strong> leads with {fmtPct(insights.strongestSection.avgOfAvgs)} average
                  completion, while <strong>{insights.weakestSection.label}</strong> trails at {fmtPct(insights.weakestSection.avgOfAvgs)} —
                  a gap of {fmtPct(insights.strongestSection.avgOfAvgs - insights.weakestSection.avgOfAvgs)}.
                </li>
              )}
              {insights.weakestCourse && (
                <li>
                  <strong>{insights.weakestCourse.label}</strong>{insights.weakestCourse.code ? ` (${insights.weakestCourse.code})` : ""} has the
                  highest not-started rate in {insights.weakestCourse.branch}, with {(insights.weakestCourse.notStartedRate * 100).toFixed(0)}% of
                  students yet to begin.
                </li>
              )}
              {totalAtRiskCourses > 0 && (
                <li>
                  <strong>{totalAtRiskCourses}</strong> course{totalAtRiskCourses !== 1 ? " instances" : " instance"} across sections
                  {" "}(a course counted separately in each section it's enabled for) sit below the {courseRiskThreshold}% course-risk
                  threshold — flagged with an "At Risk" badge on the course-wise charts below.
                </li>
              )}
              <li>
                <strong>{insights.totalAtRisk}</strong> student{insights.totalAtRisk !== 1 ? "s" : ""} ({((insights.totalAtRisk / insights.totalEvaluable) * 100 || 0).toFixed(1)}%
                of those covered) have an average completion below the {threshold}% threshold and may need follow-up.
              </li>
              {insights.totalPasswordIssues > 0 && (
                <li>
                  <strong>{insights.totalPasswordIssues}</strong> student{insights.totalPasswordIssues !== 1 ? "s" : ""} across
                  {" "}{Object.keys(insights.pwBySection).length} section{Object.keys(insights.pwBySection).length !== 1 ? "s" : ""} have
                  not set a CodeTantra password yet and likely have no recorded progress at all — flagged separately below.
                </li>
              )}
              {insights.totalNotApplicable > 0 && (
                <li>
                  <strong>{insights.totalNotApplicable}</strong> student{insights.totalNotApplicable !== 1 ? "s" : ""} show
                  {" "}"--" against every course in this report — meaning none of the uploaded courses are enabled for
                  them — and are excluded from the completion averages above, listed separately under "No Enabled Courses."
                </li>
              )}
            </ul>
          </div>

          {/* enrollment / activation summary — mirrors the source dashboard's group table.
              Started / Not Started / Not Applicable are computed per student from that
              student's own enabled course cells, so this table is correct whether every
              group in the workbook has the same courses enabled or each group has a
              different subset (e.g. 3 courses enabled for one group, 2 for another) —
              nothing here assumes a fixed course count. */}
          <div data-pdf-block="true" className="cip-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 26 }}>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY }}>
              Enrollment &amp; Activation Summary
            </div>
            <table className="cip-table" style={{ marginTop: 14 }}>
              <thead>
                <tr>
                  <th style={{ width: "5%" }}>S.No</th>
                  <th>Group</th>
                  <th>Started ({insights.enrollmentTotals.started})</th>
                  <th>Not Started ({insights.enrollmentTotals.notStarted})</th>
                  {insights.enrollmentTotals.notApplicable > 0 && (
                    <th>Not Applicable ({insights.enrollmentTotals.notApplicable})</th>
                  )}
                  <th>Password Not Set ({insights.enrollmentTotals.passwordNotSet})</th>
                  <th>Sub Total ({insights.enrollmentTotals.subTotal})</th>
                </tr>
              </thead>
              <tbody>
                {insights.enrollment.map((r, i) => (
                  <tr key={r.label}>
                    <td style={{ fontSize: 12, color: SLATE }}>{i + 1}</td>
                    <td>
                      <span style={{
                        display: "inline-block", fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 12.5,
                        color: NAVY_SOFT, background: "#EAF3F8", border: `1px solid #C7DFEA`, borderRadius: 4,
                        padding: "2px 8px",
                      }}>
                        {r.label}
                      </span>
                    </td>
                    <td style={{ color: r.started > 0 ? NAVY_SOFT : INK, fontWeight: 600 }}>{r.started}</td>
                    <td style={{ color: r.notStarted > 0 ? RUST : INK, fontWeight: r.notStarted > 0 ? 600 : 400 }}>{r.notStarted}</td>
                    {insights.enrollmentTotals.notApplicable > 0 && (
                      <td style={{ color: r.notApplicable > 0 ? SLATE : INK, fontWeight: r.notApplicable > 0 ? 600 : 400 }}>{r.notApplicable}</td>
                    )}
                    <td style={{ color: r.passwordNotSet > 0 ? GOLD : INK, fontWeight: r.passwordNotSet > 0 ? 600 : 400 }}>{r.passwordNotSet}</td>
                    <td style={{ fontWeight: 600 }}>{r.subTotal}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr style={{ borderTop: `2px solid ${NAVY}` }}>
                  <td style={{ fontWeight: 700, color: NAVY }}></td>
                  <td style={{ fontWeight: 700, color: NAVY }}>Total</td>
                  <td style={{ fontWeight: 700 }}>{insights.enrollmentTotals.started}</td>
                  <td style={{ fontWeight: 700 }}>{insights.enrollmentTotals.notStarted}</td>
                  {insights.enrollmentTotals.notApplicable > 0 && (
                    <td style={{ fontWeight: 700 }}>{insights.enrollmentTotals.notApplicable}</td>
                  )}
                  <td style={{ fontWeight: 700 }}>{insights.enrollmentTotals.passwordNotSet}</td>
                  <td style={{ fontWeight: 700 }}>{insights.enrollmentTotals.subTotal}</td>
                </tr>
              </tfoot>
            </table>
          </div>

          {/* section-wise chart — flows with the rest of the report; the print
              engine only pushes it to a new page if it doesn't fit on the current
              one (see .cip-chart-card rule in the stylesheet below) */}
          <div data-pdf-block="true" className="cip-card cip-chart-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 16 }}>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY, marginBottom: 4 }}>
              Average Completion by Section
            </div>
            <div style={{ fontSize: 12, color: SLATE, marginBottom: 14 }}>Mean of each student's average across all enabled courses</div>
            <BarRows
              rows={insights.sections.map((s) => ({ label: s.label, value: s.avgOfAvgs, color: barColor(s.avgOfAvgs) }))}
              labelWidth={130}
            />
          </div>

          {/* course-wise chart per section — packed onto pages by the print engine
              based on each card's actual measured height, instead of always
              starting a fresh page (which left huge blank gaps below short charts).
              Each section's bar list is built from sec.perCourse, which already
              only includes the courses actually enabled for that section (see the
              enabledCount > 0 filter above), so a section with 2 enabled courses
              shows exactly 2 bars and a section with 3 shows 3 — no course list is
              assumed to be the same size across sections. */}
          {insights.sections.map((sec) => {
            const atRiskCourses = sec.perCourse.filter((c) => c.avg < courseRiskThreshold);
            return (
              <div
                key={sec.label}
                data-pdf-block="true"
                className="cip-card cip-chart-card"
                style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 16 }}
              >
                <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY, marginBottom: 4 }}>
                  Course-wise Average Completion — {sec.label}
                </div>
                <div style={{ fontSize: 12, color: SLATE, marginBottom: 14 }}>
                  {sec.studentCount} students in this section · {sec.perCourse.length} course{sec.perCourse.length !== 1 ? "s" : ""} enabled
                  {atRiskCourses.length > 0 && (
                    <span style={{ color: RUST, fontWeight: 600 }}> · {atRiskCourses.length} at risk (below {courseRiskThreshold}%)</span>
                  )}
                </div>
                {sec.perCourse.length === 0 ? (
                  <div style={{ fontSize: 13, color: SLATE }}>None of the uploaded courses are enabled for this section.</div>
                ) : (
                  <BarRows
                    rows={sec.perCourse.map((c) => ({ label: c.label, value: c.avg, color: barColor(c.avg) }))}
                    labelWidth={260}
                    flagThreshold={courseRiskThreshold}
                  />
                )}
              </div>
            );
          })}

          {/* section detail table */}
          <div data-pdf-block="true" className="cip-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 26 }}>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY, marginBottom: 10 }}>
              Section Summary
            </div>
            <table className="cip-table">
              <thead>
                <tr>
                  <th style={{ width: "6%" }}>S.No</th><th>Section</th><th>Students</th><th>Avg. Completion</th><th>At Risk</th><th>Passwords Not Set</th>
                </tr>
              </thead>
              <tbody>
                {insights.sections.map((s, i) => (
                  <tr key={s.label}>
                    <td style={{ fontSize: 12, color: SLATE }}>{i + 1}</td>
                    <td style={{ fontWeight: 600, color: NAVY }}>{s.label}</td>
                    <td>{s.studentCount}</td>
                    <td><span style={{ color: barColor(s.avgOfAvgs), fontWeight: 600 }}>{fmtPct(s.avgOfAvgs)}</span></td>
                    <td>{s.atRisk.length}</td>
                    <td>{insights.pwBySection[s.label]?.entries.length || 0}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* student performance — everyone is shown, grouped into
              at-risk / average / good / excellent completion bands, each
              independently collapsible on screen (always fully rendered
              for print/PDF export) */}
          <div data-pdf-block="true" className="cip-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 8 }}>
            <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY }}>
              Student Performance
            </div>
            <div style={{ fontSize: 12, color: SLATE, marginTop: 4 }}>
              All {insights.totalStudents} students, grouped by average completion band
            </div>
          </div>

          {insights.categorizedStudents.map((cat) => {
            const stateKey = `perf-${cat.key}`;
            const isOpen = expandedSections[stateKey] !== false;
            return (
              <div
                key={cat.key}
                data-pdf-block="true"
                className="cip-card"
                style={{
                  background: "#fff", border: `1px solid ${PAPER_LINE}`, borderLeft: `4px solid ${cat.color}`,
                  borderRadius: 4, padding: "14px 22px", marginBottom: 10,
                }}
              >
                <div
                  onClick={() => toggleSection(stateKey)}
                  style={{ display: "flex", alignItems: "center", gap: 6, cursor: "pointer", fontWeight: 600, color: NAVY, fontSize: 13.5, marginBottom: 6 }}
                  className="no-print"
                >
                  {isOpen ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                  {cat.title} <span style={{ fontWeight: 400, color: SLATE }}>({cat.range})</span>
                  <span style={{ marginLeft: "auto", color: cat.color, fontWeight: 700 }}>{cat.students.length}</span>
                </div>
                {isOpen && (
                  cat.students.length === 0 ? (
                    <div style={{ fontSize: 13, color: SLATE }}>No students in this band.</div>
                  ) : (
                    (() => {
                      // Group this band's students by their section so students
                      // from the same group sit together under their own
                      // sub-table, instead of one flat table mixing sections.
                      const bySection = {};
                      cat.students.forEach((s) => {
                        (bySection[s.sectionLabel] ||= []).push(s);
                      });
                      const sectionKeys = Object.keys(bySection).sort((a, b) => a.localeCompare(b));
                      return sectionKeys.map((secLabel) => (
                        <div key={secLabel} style={{ marginBottom: 16 }}>
                          <div style={{
                            display: "flex", alignItems: "center", gap: 8, fontSize: 12.5,
                            fontWeight: 600, color: NAVY_SOFT, margin: "4px 0 6px",
                          }}>
                            <span style={{
                              display: "inline-block", fontFamily: "'Source Serif 4', Georgia, serif",
                              color: NAVY_SOFT, background: "#EAF3F8", border: "1px solid #C7DFEA",
                              borderRadius: 4, padding: "2px 8px",
                            }}>
                              {secLabel}
                            </span>
                            <span style={{ fontWeight: 400, color: SLATE }}>{bySection[secLabel].length} student{bySection[secLabel].length !== 1 ? "s" : ""}</span>
                          </div>
                          <table className="cip-table" style={{ tableLayout: "fixed" }}>
                            <colgroup>
                              <col style={{ width: "6%" }} />
                              <col style={{ width: "13%" }} />
                              <col style={{ width: cat.key === "atRisk" ? "21%" : "33%" }} />
                              <col style={{ width: "19%" }} />
                              <col style={{ width: "9%" }} />
                              {cat.key === "atRisk" && <col style={{ width: "32%" }} />}
                            </colgroup>
                            <thead>
                              <tr>
                                <th>S.No</th><th>Member Id</th><th>Name</th><th>Group</th><th>Avg.</th>
                                {cat.key === "atRisk" && <th>Courses not started</th>}
                              </tr>
                            </thead>
                            <tbody>
                              {bySection[secLabel].map((s, i) => (
                                <tr key={i}>
                                  <td style={{ fontSize: 12, color: SLATE }}>{i + 1}</td>
                                  <td style={{ fontSize: 12, color: SLATE }}>{s.id}</td>
                                  <td>{s.name}</td>
                                  <td style={{ fontSize: 12, color: NAVY_SOFT, fontWeight: 600 }}>{s.sectionLabel}</td>
                                  <td style={{ color: cat.color, fontWeight: 600 }}>{s.avg === null ? "—" : fmtPct(s.avg)}</td>
                                  {cat.key === "atRisk" && (
                                    <td style={{ fontSize: 12, color: SLATE }}>{s.notStartedCourses.join(", ") || "—"}</td>
                                  )}
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      ));
                    })()
                  )
                )}
              </div>
            );
          })}

          {/* password not set — each group is its own export chunk so the PDF
              export doesn't have to rasterize potentially hundreds of student
              rows in a single pass */}
          {insights.totalPasswordIssues > 0 && (
            <>
              <div data-pdf-block="true" className="cip-card" style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "18px 22px", marginBottom: 8, marginTop: 16 }}>
                <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: 16, fontWeight: 600, color: NAVY }}>
                  Passwords Not Set
                </div>
              </div>
              {Object.entries(insights.pwBySection).map(([label, g]) => (
                <div
                  key={label}
                  data-pdf-block="true"
                  className="cip-card"
                  style={{ background: "#fff", border: `1px solid ${PAPER_LINE}`, borderRadius: 4, padding: "14px 22px", marginBottom: 10 }}
                >
                  <div
                    onClick={() => toggleSection(label)}
                    style={{ display: "flex", alignItems: "center", gap: 6, cursor: "pointer", fontWeight: 600, color: NAVY, fontSize: 13.5, marginBottom: 6 }}
                    className="no-print"
                  >
                    {expandedSections[label] ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                    {label} — {g.entries.length} student{g.entries.length !== 1 ? "s" : ""}
                  </div>
                  {expandedSections[label] === false ? null : (
                    <table className="cip-table">
                      <thead><tr><th style={{ width: "8%" }}>S.No</th><th>Name</th><th>Email</th><th>Account Created</th></tr></thead>
                      <tbody>
                        {g.entries.map((e, i) => (
                          <tr key={i}><td style={{ fontSize: 12, color: SLATE }}>{i + 1}</td><td>{e.name}</td><td>{e.email}</td><td>{e.createdTime}</td></tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
              ))}
            </>
          )}

          {/* footer */}
          <div data-pdf-block="true" style={{ textAlign: "center", color: SLATE, fontSize: 11.5, padding: "18px 0 40px", borderTop: `1px solid ${PAPER_LINE}`, marginTop: 10 }}>
            Compiled from CodeTantra group-wise course and password-status exports · Report generated {generatedDate}
          </div>
        </div>
      )}
    </div>
  );
}